Repository paritytech/polkassembly, pull requests merged in 2019-12, with the labels that each got.

#56 Added proper error handling for graphql
  auth-server/src/resolvers/mutation/changeEmail.ts
  auth-server/src/resolvers/mutation/signup.ts
  auth-server/src/services/auth.ts
  auth-server/src/utils/getTokenFromReq.ts
Labels: PR-1-please review

#64 Remove actions
  .github/workflows/auth-server-linting.deactivted
  .github/workflows/front-end-linting.deactivated
Labels: PR-2-insubstantial

#65 Update hasura
  hasura/docker-compose.yaml.example
  hasura/hasura-migrations/migrations/1575300356679_update_permission_user_public_table_posts/down.yaml
  hasura/hasura-migrations/migrations/1575300356679_update_permission_user_public_table_posts/up.yaml
Labels: PR-1-please review

#66 Allow replies aggregations for users
  hasura/hasura-migrations/migrations/1575366466304_update_permission_user_public_table_replies/down.yaml
  hasura/hasura-migrations/migrations/1575366466304_update_permission_user_public_table_replies/up.yaml
Labels: PR-2-insubstantial

#74 Fix several bugs in the front-end
  front-end/src/index.tsx
  front-end/src/screens/CreatePost/index.tsx
  front-end/src/screens/MenuBar/index.tsx
  front-end/src/services/auth.service.tsx
Labels: PR-1-please review

#79 Only show button for loggedin users
  front-end/src/screens/Home/Home.tsx
Labels: PR-1-please review

#78 Better error handling and bug fixes
  front-end/src/generated/auth-graphql.tsx
  front-end/src/index.tsx
  front-end/src/screens/LoginForm/index.tsx
  front-end/src/screens/SignupForm/index.tsx
  front-end/src/services/auth-queries.ts
  hasura/hasura-migrations/migrations/1575643372009_update_permission_user_public_table_replies/down.yaml
  hasura/hasura-migrations/migrations/1575643372009_update_permission_user_public_table_replies/up.yaml
  hasura/hasura-migrations/migrations/metadata.json
Labels: PR-1-please review

#86 Email verification page
  auth-server/src/services/auth.ts
  auth-server/src/services/email.ts
  front-end/package.json
  front-end/src/App.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/hooks/index.ts
  front-end/src/hooks/useRouter.ts
  front-end/src/screens/CreatePost/index.tsx
  front-end/src/screens/Home/HomeContent.tsx
  front-end/src/screens/Home/index.tsx
  front-end/src/screens/LoginForm/index.tsx
  front-end/src/screens/MenuBar/index.tsx
  front-end/src/screens/Post/index.tsx
  front-end/src/screens/SignupForm/index.tsx
  front-end/src/screens/VerifyEmail/index.tsx
  front-end/src/screens/VerifyEmail/query.ts
  front-end/yarn.lock
Labels: PR-1-please review

#99 Refactor user context and Apollo call
  front-end/src/App.tsx
  front-end/src/components/Apollo.tsx
  front-end/src/context/UserDetailsContext.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/index.tsx
  front-end/src/screens/MenuBar/index.tsx
  front-end/src/screens/Post/index.tsx
  front-end/src/screens/Post/query.ts
  front-end/src/screens/VerifyEmail/index.tsx
  front-end/src/services/auth.service.tsx
Labels: PR-1-please review

#85 Erler remove bootstrap
  front-end/package.json
  front-end/src/components/DiscussionCard.tsx
  front-end/src/screens/CreatePost/index.tsx
  front-end/src/screens/Discussions/Discussions.tsx
  front-end/src/screens/Home/HomeContent.tsx
  front-end/src/screens/MenuBar/index.tsx
  front-end/src/screens/Post/Post.tsx
  front-end/src/screens/Proposals/Proposals.tsx
  front-end/src/ui-components/Button.tsx
  front-end/src/ui-components/Form.tsx
  front-end/src/ui-components/GlobalStyle.tsx
  front-end/src/ui-components/Tag.tsx
  front-end/src/ui-components/TextArea.tsx
  front-end/yarn.lock
Labels: PR-1-please review

#93 Setup test suite
  auth-server/.dockerignore
  auth-server/.gitignore
  auth-server/README.md
  auth-server/docker-compose-test.yaml
  auth-server/knexfile.js
  auth-server/package.json
  auth-server/src/model/EmailVerificationToken.ts
  auth-server/src/model/PasswordResetToken.ts
  auth-server/src/model/RefreshToken.ts
  auth-server/src/model/User.ts
  auth-server/src/model/connection.ts
  auth-server/test.Dockerfile
  auth-server/test/resolvers/query/user.spec.ts
  auth-server/test/setup.spec.ts
  auth-server/yarn.lock
Labels: PR-1-please review

#107 Delete old dockerfile
  auth-server/Dockerfile
Labels: PR-1-please review, PR-2-insubstantial

#110 Move gitlab ci to root
  .gitlab-ci.yml
Labels: PR-2-insubstantial

#111 Issue 102 - New Post Button Positioning
  front-end/src/screens/Discussions/Discussions.tsx
  front-end/src/screens/Home/HomeContent.tsx
  front-end/src/ui-components/Button.tsx
Labels: PR-1-please review

#119 recursive path
  .gitlab-ci.yml
Labels: PR-2-insubstantial

#115 Add helper script and slightly change docker-compose
  README.md
  auth-server/.gitignore
  auth-server/README.md
  auth-server/docker-compose.yaml.example
  front-end/.gitignore
  hasura/docker-compose.yaml.example
  launch.sh
Labels: PR-1-please review

#117 Throwing proper error if username and email is already taken
  auth-server/src/services/auth.ts
Labels: PR-1-please review

#121 Added email validate tests
  auth-server/test/utils/validateEmail.spec.ts
Labels: PR-1-please review

#124 change name test and other test fixes
  auth-server/test/resolvers/mutation/changeName.spec.ts
  auth-server/test/resolvers/mutation/login.spec.ts
  auth-server/test/resolvers/mutation/signup.spec.ts
  auth-server/test/utils/validateEmail/validateEmail.spec.ts
Labels: PR-6-grumbles

#131 tests for change password/verifyemail
  auth-server/test/resolvers/mutation/changePassword.spec.ts
  auth-server/test/resolvers/mutation/verifyEmail.spec.ts
Labels: PR-1-please review

#136 Add test and refactor
  auth-server/src/resolvers/mutation/logout.ts
  auth-server/src/services/auth.ts
  auth-server/src/types.ts
  auth-server/src/utils/getUserFromUserId.ts
  auth-server/src/utils/getUserIdFromJWT.ts
  auth-server/src/utils/messages.ts
  auth-server/test/resolvers/mutation/changeName.spec.ts
  auth-server/test/resolvers/mutation/changePassword.spec.ts
  auth-server/test/resolvers/mutation/login.spec.ts
  auth-server/test/resolvers/mutation/logout.spec.ts
  auth-server/test/resolvers/mutation/signup.spec.ts
  auth-server/test/resolvers/mutation/verifyEmail.spec.ts
  front-end/src/screens/Home/HomeContent.tsx
  front-end/src/types.ts
Labels: PR-1-please review

#132 EditablePostContent fix
  front-end/src/components/PostOrCommentForm.tsx
  front-end/src/screens/CreatePost/index.tsx
  front-end/src/screens/Discussions/Discussions.tsx
  front-end/src/screens/Home/HomeContent.tsx
  front-end/src/screens/LoginForm/index.tsx
  front-end/src/screens/Post/Comment.tsx
  front-end/src/screens/Post/Comments.tsx
  front-end/src/screens/Post/CreateRootComment.tsx
  front-end/src/screens/Post/EditablePostContent.tsx
  front-end/src/screens/Post/Post.tsx
  front-end/src/screens/SignupForm/index.tsx
  front-end/src/ui-components/Button.tsx
  front-end/src/ui-components/TextArea.tsx
Labels: PR-1-please review

#153 Typo
  auth-server/src/utils/messages.ts
Labels: PR-2-insubstantial

#151 Added username mutation
  auth-server/README.md
  auth-server/src/resolvers/index.ts
  auth-server/src/resolvers/mutation/changeEmail.ts
  auth-server/src/resolvers/mutation/changeUsername.ts
  auth-server/src/schema/index.ts
  auth-server/src/schema/mutation/changeUsername.ts
  auth-server/src/services/auth.ts
  auth-server/src/services/email.ts
  auth-server/src/utils/messages.ts
  auth-server/test/resolvers/mutation/changeEmail.spec.ts
  auth-server/test/resolvers/mutation/changeUsername.spec.ts
  auth-server/test/resolvers/mutation/logout.spec.ts
Labels: PR-1-please review

#158 Test docker
  auth-server/README.md
  auth-server/docker-compose-test.yaml
  auth-server/package.json
  auth-server/src/index.ts
  auth-server/src/services/auth.ts
  auth-server/test.Dockerfile
Labels: PR-1-please review

#159 Reset pw
  front-end/src/App.tsx
  front-end/src/components/Modal.tsx
  front-end/src/context/ModalContext.tsx
  front-end/src/generated/auth-graphql.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/screens/LoginForm/index.tsx
  front-end/src/screens/RequestResetPassword/ResetPassword/index.tsx
  front-end/src/screens/RequestResetPassword/ResetPassword/query.ts
  front-end/src/screens/RequestResetPassword/index.tsx
  front-end/src/screens/RequestResetPassword/query.ts
  front-end/src/screens/SignupForm/index.tsx
  front-end/src/screens/VerifyEmail/index.tsx
  front-end/src/types.ts
  front-end/src/ui-components/Form.tsx
  front-end/src/ui-components/Modal.tsx
  launch.sh
Labels: PR-1-please review

#161 Topics refactor
  front-end/src/components/PostOrCommentForm.tsx
  front-end/src/screens/CreatePost/TopicsRadio.tsx
  front-end/src/screens/CreatePost/index.tsx
  front-end/src/screens/Post/EditablePostContent.tsx
  front-end/src/ui-components/Field.tsx
  front-end/src/ui-components/Form.tsx
  front-end/src/ui-components/Group.tsx
  front-end/src/ui-components/Input.tsx
Labels: PR-1-please review

#168 change postgres service name in test postgres
  auth-server/docker-compose-test.yaml
Labels: PR-1-please review
