Repository paritytech/polkassembly, pull requests merged in 2019-11, with the labels that each got.

#10 Create replies_count computed field
  hasura/docker-compose.yaml
  hasura/graphql-engine/Dockerfile
  hasura/hasura-migrations/migrations/1574246024580_run_sql_migration/down.yaml
  hasura/hasura-migrations/migrations/1574246024580_run_sql_migration/up.yaml
  hasura/hasura-migrations/migrations/metadata.json
Labels: A0-pleasereview

#9 Converted auth server to typescript
  auth-server/.editorconfig
  auth-server/.eslintignore
  auth-server/.eslintrc.json
  auth-server/.gitignore
  auth-server/README.md
  auth-server/app.js
  auth-server/config/passport.js
  auth-server/controllers/graphql.js
  auth-server/controllers/user.js
  auth-server/db/errors.js
  auth-server/db/migrations/20180917160913_users.js
  auth-server/db/schema.js
  auth-server/knexfile.js
  auth-server/migrations/20180917160913_users.js
  auth-server/migrations/20191120202513_refresh_token.js
  auth-server/package.json
  auth-server/src/controllers/graphql.ts
  auth-server/src/controllers/upload.ts
  auth-server/src/controllers/user.ts
  auth-server/src/index.ts
  auth-server/src/model/RefreshToken.ts
  auth-server/src/model/User.ts
  auth-server/src/model/errors.ts
  auth-server/src/services/auth.ts
  auth-server/src/types.ts
  auth-server/test/.gitkeep
  auth-server/tsconfig.json
  auth-server/yarn.lock
Labels: A0-pleasereview

#25 Add lint workflow for auth-server PR
  .github/workflows/main.yml
  auth-server/src/controllers/user.ts
Labels: PR-1-please review

#27 created change name api
  auth-server/README.md
  auth-server/src/controllers/user.ts
  auth-server/src/index.ts
  auth-server/src/services/auth.ts
Labels: PR-1-please review

#18 Change password API
  auth-server/README.md
  auth-server/src/controllers/upload.ts
  auth-server/src/controllers/user.ts
  auth-server/src/index.ts
  auth-server/src/services/auth.ts
  auth-server/src/types.ts
Labels: PR-1-please review

#34 Add migration tracking in Readme
  hasura/README.md
Labels: PR-1-please review, PR-2-insubstantial

#42 Permissions related to post creation
  hasura/hasura-migrations/migrations/1574971921162_update_permission_user_public_table_replies/down.yaml
  hasura/hasura-migrations/migrations/1574971921162_update_permission_user_public_table_replies/up.yaml
  hasura/hasura-migrations/migrations/1574977595328_update_permission_user_public_table_posts/down.yaml
  hasura/hasura-migrations/migrations/1574977595328_update_permission_user_public_table_posts/up.yaml
Labels: PR-2-insubstantial

#43 Add front end
  .github/workflows/lint.yml
  front-end/.eslintignore
  front-end/.eslintrc.json
  front-end/.gitignore
  front-end/README.md
  front-end/codegen.yml
  front-end/package.json
  front-end/public/favicon.ico
  front-end/public/index.html
  front-end/public/logo192.png
  front-end/public/logo512.png
  front-end/public/manifest.json
  front-end/public/robots.txt
  front-end/src/App.test.tsx
  front-end/src/App.tsx
  front-end/src/components/DiscussionCard.tsx
  front-end/src/components/GlobalStyle.tsx
  front-end/src/context/UserDetailsContext.tsx
  front-end/src/fonts.css
  front-end/src/fragments/index.ts
  front-end/src/fragments/user.fragment.ts
  front-end/src/generated/graphql.tsx
  front-end/src/index.tsx
  front-end/src/logo.svg
  front-end/src/react-app-env.d.ts
  front-end/src/screens/CreatePost/index.tsx
  front-end/src/screens/CreatePost/query.ts
  front-end/src/screens/Home/Home.tsx
  front-end/src/screens/Home/index.tsx
  front-end/src/screens/Home/query.ts
  front-end/src/screens/LoginForm/index.tsx
  front-end/src/screens/MenuBar/index.tsx
  front-end/src/screens/Post/NoPostFound.tsx
  front-end/src/screens/Post/Post.tsx
  front-end/src/screens/Post/Replies.tsx
  front-end/src/screens/Post/index.tsx
  front-end/src/screens/Post/query.ts
  front-end/src/screens/SignupForm/index.tsx
  front-end/src/serviceWorker.ts
  front-end/src/services/auth.service.tsx
  front-end/src/types.ts
  front-end/src/util/parseJWT.tsx
  front-end/tsconfig.json
  front-end/yarn.lock
Labels: PR-1-please review

#44 Readme update
  README.md
Labels: PR-2-insubstantial

#55 Deactivate workflow actions..
  .github/workflows/auth-server-linting.deactivted
  .github/workflows/front-end-linting.deactivated
Labels: PR-2-insubstantial
