Repository paritytech/polkassembly, pull requests merged in 2020-04, with the labels that each got.

#590 Moved reply form at the bottom of post
  front-end/src/components/Post/Post.tsx
  front-end/src/components/Post/PostCommentForm.tsx
Labels: PR-1-please review

#597 Method on GovernanceCard
  front-end/src/components/GovernanceCard.tsx
  front-end/src/components/Listings/MotionsListing.tsx
  front-end/src/components/Listings/ProposalsListing.tsx
  front-end/src/components/Listings/ReferendaListing.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/screens/OnChain/Motions/query.ts
  front-end/src/screens/OnChain/Proposals/query.ts
  front-end/src/screens/OnChain/Referenda/query.ts
  front-end/src/ui-components/Address.tsx
  front-end/src/ui-components/OnchainCreationLabel.tsx
  front-end/src/ui-components/StatusTag.tsx
  front-end/src/ui-components/TopicTag.tsx
Labels: PR-1-please review

#595 Add progress bar and adaptive quorum bias for referenda
  front-end/package.json
  front-end/src/components/Balance.tsx
  front-end/src/components/Post/GovernanceSideBar/Proposals/ProposalVoteInfo.tsx
  front-end/src/components/Post/GovernanceSideBar/Referenda/ReferendumVoteInfo.tsx
  front-end/src/components/Post/GovernanceSideBar/Referenda/VoteReferendum.tsx
  front-end/src/components/Post/GovernanceSideBar/index.tsx
  front-end/src/types.ts
  front-end/src/ui-components/VoteProgress.tsx
  front-end/src/util/formatBnBalance.ts
  front-end/src/util/getEncodedAddress.ts
  front-end/src/util/getPassingThreshold.ts
  front-end/src/util/newton-raphson.ts
  front-end/src/util/solveQuadraticEquation.ts
  front-end/yarn.lock
Labels: PR-1-please review

#602 [chain-db-watcher] Unifyed linting accross projects
  chain-db-watcher/.eslintignore
  chain-db-watcher/.eslintrc.json
  chain-db-watcher/package.json
  chain-db-watcher/src/generated/chain-db-graphql.ts
  chain-db-watcher/src/generated/discussion-db-graphql.ts
  chain-db-watcher/src/graphql_helpers.ts
  chain-db-watcher/src/sync/getter.ts
  chain-db-watcher/src/sync/index.ts
  chain-db-watcher/src/sync/utils.ts
  chain-db-watcher/tsconfig.json
  chain-db-watcher/yarn.lock
Labels: PR-1-please review

#608 Logging connection state and errors
  chain-db-watcher/src/index.ts
  chain-db-watcher/src/sync/index.ts
Labels: PR-1-please review

#612 Silence lint warnings in tests
  auth-server/test/resolvers/mutation/logout.spec.ts
  auth-server/test/resolvers/mutation/postSubscribe.spec.ts
  auth-server/test/resolvers/mutation/postUnsubscribe.spec.ts
  auth-server/test/resolvers/query/subscription.spec.ts
  auth-server/test/resolvers/query/users.spec.ts
Labels: PR-1-please review

#611 Enforce headers in eslint
  auth-server/.eslintrc.json
  auth-server/knexfile.js
  auth-server/migrations/20180917160913_users.js
  auth-server/migrations/20191120202513_refresh_token.js
  auth-server/migrations/20191127101810_users_verified.js
  auth-server/migrations/20191127103957_email_verification_token.js
  auth-server/migrations/20191203094429_password_reset_token.js
  auth-server/migrations/20191231152732_post_subscription.js
  auth-server/migrations/20200111182158_undo_email_change_token.js
  auth-server/migrations/20200113102520_address.js
  auth-server/migrations/20200219104712_users_index.js
  auth-server/migrations/20200219105704_refresh_tokens_index.js
  auth-server/migrations/20200219105905_email_verification_token_index.js
  auth-server/migrations/20200219110001_password_reset_token_index.js
  auth-server/migrations/20200219110123_post_subscription_index.js
  auth-server/migrations/20200219110317_undo_email_change_token_index.js
  auth-server/migrations/20200225193118_notification.js
  auth-server/migrations/20200305162755_content_report.js
  auth-server/migrations/20200313181311_report_content_network.js
  auth-server/package.json
  auth-server/src/schema/mutation/reportContent.ts
  auth-server/src/utils/emailTemplates.ts
  auth-server/test/resolvers/mutation/addressLinkConfirm.spec.ts
  auth-server/test/resolvers/mutation/addressLinkStart.spec.ts
  auth-server/test/resolvers/mutation/addressUnlink.spec.ts
  auth-server/test/resolvers/mutation/changeEmail.spec.ts
  auth-server/test/resolvers/mutation/changeName.spec.ts
  auth-server/test/resolvers/mutation/changeNotificationPreference.spec.ts
  auth-server/test/resolvers/mutation/changePassword.spec.ts
  auth-server/test/resolvers/mutation/changeUsername.spec.ts
  auth-server/test/resolvers/mutation/login.spec.ts
  auth-server/test/resolvers/mutation/logout.spec.ts
  auth-server/test/resolvers/mutation/postSubscribe.spec.ts
  auth-server/test/resolvers/mutation/postUnsubscribe.spec.ts
  auth-server/test/resolvers/mutation/requestResetPassword.spec.ts
  auth-server/test/resolvers/mutation/resendVerifyEmailToken.spec.ts
  auth-server/test/resolvers/mutation/signup.spec.ts
  auth-server/test/resolvers/mutation/undoEmailChange.spec.ts
  auth-server/test/resolvers/mutation/verifyEmail.spec.ts
  auth-server/test/resolvers/query/subscription.spec.ts
  auth-server/test/resolvers/query/user.spec.ts
  auth-server/test/resolvers/query/users.spec.ts
  auth-server/test/rewiremock.ts
  auth-server/test/services/email/email.spec.ts
  auth-server/test/setup.spec.ts
  auth-server/test/utils/validateEmail/validateEmail.spec.ts
  auth-server/test/utils/validateName/ValidateName.spec.ts
  auth-server/test/utils/validateUsername/validateUsername.spec.ts
  auth-server/yarn.lock
  chain-db-watcher/.eslintrc.json
  chain-db-watcher/package.json
  chain-db-watcher/yarn.lock
  front-end/.eslintrc.json
  front-end/package.json
  front-end/src/context/ApiContext.tsx
  front-end/yarn.lock
  header.js
Labels: PR-1-please review

#627 Added missing id in queries
  front-end/src/components/Post/GovernanceSideBar/query.ts
  front-end/src/generated/graphql.tsx
  front-end/src/screens/OnChain/Motions/query.ts
  front-end/src/screens/OnChain/Proposals/query.ts
  front-end/src/screens/OnChain/Referenda/query.ts
Labels: PR-1-please review

#633 Fix double error and some styling
  front-end/src/components/Login/Web3Login.tsx
Labels: PR-1-please review

#637 Form validation fix
  front-end/src/components/Comment/Comments.tsx
  front-end/src/components/ContentForm.tsx
  front-end/src/components/Modal.tsx
  front-end/src/components/Notifications.tsx
  front-end/src/components/Post/PostCommentForm.tsx
  front-end/src/screens/Home/index.tsx
  front-end/src/screens/NotFound/index.tsx
  front-end/src/screens/RequestResetPassword/ResetPassword/index.tsx
  front-end/src/screens/RequestResetPassword/index.tsx
  front-end/src/screens/Settings/email.tsx
  front-end/src/screens/Settings/username.tsx
  front-end/src/screens/UndoEmailChange/index.tsx
  front-end/src/screens/VerifyEmail/index.tsx
  front-end/src/ui-components/Field.tsx
  front-end/src/ui-components/Group.tsx
  front-end/src/ui-components/Loader.tsx
  front-end/src/ui-components/MarkdownEditor.tsx
Labels: PR-1-please review

#636 Align tsconfig with auth-server
  chain-db-watcher/tsconfig.json
Labels: PR-1-please review

#644 Post title fix
  front-end/src/components/Post/PostContent.tsx
Labels: PR-1-please review

#648 Fix threshold
  front-end/package.json
  front-end/yarn.lock
  util/CHANGELOG.md
  util/package.json
  util/src/getPassingThreshold.ts
Labels: PR-1-please review

#650 Fv helmify
  .gitlab-ci.yml
  kubernetes/polkassembly/.helmignore
  kubernetes/polkassembly/Chart.yaml
  kubernetes/polkassembly/auth-server-config.yaml
  kubernetes/polkassembly/auth-server-deployment.yaml
  kubernetes/polkassembly/auth-server-secrets.yaml
  kubernetes/polkassembly/auth-server-service.yaml
  kubernetes/polkassembly/chain-db-watcher-config.yaml
  kubernetes/polkassembly/chain-db-watcher-deployment.yaml
  kubernetes/polkassembly/front-end-deployment.yaml
  kubernetes/polkassembly/front-end-ingress.yaml
  kubernetes/polkassembly/front-end-service.yaml
  kubernetes/polkassembly/hasura-config.yaml
  kubernetes/polkassembly/hasura-deployment.yaml
  kubernetes/polkassembly/hasura-secrets.yaml
  kubernetes/polkassembly/hasura-service.yaml
  kubernetes/polkassembly/regcred-secret.yaml
  kubernetes/polkassembly/templates/_helpers.tpl
  kubernetes/polkassembly/templates/auth-server-config.yaml
  kubernetes/polkassembly/templates/auth-server-deployment.yaml
  kubernetes/polkassembly/templates/auth-server-secrets.yaml
  kubernetes/polkassembly/templates/auth-server-service.yaml
  kubernetes/polkassembly/templates/chain-db-watcher-config.yaml
  kubernetes/polkassembly/templates/chain-db-watcher-deployment.yaml
  kubernetes/polkassembly/templates/cloudsql-instance-credentials-secret.yaml
  kubernetes/polkassembly/templates/frontend-deployment.yaml
  kubernetes/polkassembly/templates/frontend-ingress.yaml
  kubernetes/polkassembly/templates/frontend-service.yaml
  kubernetes/polkassembly/templates/hasura-config.yaml
  kubernetes/polkassembly/templates/hasura-deployment.yaml
  kubernetes/polkassembly/templates/hasura-secret.yaml
  kubernetes/polkassembly/templates/hasura-service.yaml
  kubernetes/polkassembly/values-dashboards-cluster-1.yaml
  kubernetes/polkassembly/values-parity-prod.yaml
  kubernetes/polkassembly/values.yaml
Labels: P1-asap, s-4-devops

#681 Fixed overflow for arguments
  front-end/src/ui-components/OnchainInfoWrapper.tsx
Labels: PR-1-please review

#695 Check error message type
  front-end/src/components/Comment/EditableCommentContent.tsx
  front-end/src/components/EditablePostContent.tsx
  front-end/src/components/Login/Web2Login.tsx
  front-end/src/components/Login/Web3Login.tsx
  front-end/src/components/Post/PostCommentForm.tsx
  front-end/src/components/ReportButton/index.tsx
  front-end/src/screens/CreatePost/TopicsRadio.tsx
  front-end/src/screens/CreatePost/index.tsx
  front-end/src/screens/DiscussionPost/index.tsx
  front-end/src/screens/Discussions/Discussions.tsx
  front-end/src/screens/Home/LatestDiscussions/index.tsx
  front-end/src/screens/Home/LatestMotions/index.tsx
  front-end/src/screens/Home/LatestProposals/index.tsx
  front-end/src/screens/Home/LatestReferenda/index.tsx
  front-end/src/screens/Home/LatestTreasury/index.tsx
  front-end/src/screens/MotionPost/index.tsx
  front-end/src/screens/NotificationSettings/index.tsx
  front-end/src/screens/OnChain/Motions/index.tsx
  front-end/src/screens/OnChain/Proposals/index.tsx
  front-end/src/screens/OnChain/Referenda/index.tsx
  front-end/src/screens/OnChain/Treasury/index.tsx
  front-end/src/screens/ProposalPost/index.tsx
  front-end/src/screens/ReferendumPost/index.tsx
  front-end/src/screens/RequestResetPassword/index.tsx
  front-end/src/screens/ResetPassword/index.tsx
  front-end/src/screens/Settings/email.tsx
  front-end/src/screens/Settings/fullname.tsx
  front-end/src/screens/Settings/password.tsx
  front-end/src/screens/Settings/username.tsx
  front-end/src/screens/SignupForm/index.tsx
  front-end/src/screens/TreasuryPost/index.tsx
  front-end/src/screens/UndoEmailChange/index.tsx
  front-end/src/screens/VerifyEmail/index.tsx
Labels: PR-1-please review

#707 Comment box width fix
  front-end/src/components/Comment/Comment.tsx
Labels: PR-1-please review

#725 Added link to issues tracker
  front-end/src/components/Footer/index.tsx
Labels: PR-1-please review

#687 Fixed repository fields
  auth-server/package.json
  chain-db-watcher/package.json
  front-end/package.json
Labels: PR-1-please review

#677 Default address frontend
  front-end/src/context/UserDetailsContext.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/screens/Settings/address.tsx
  front-end/src/screens/Settings/query.ts
  front-end/src/types.ts
Labels: PR-1-please review

#729 Web3 Signup Styling
  front-end/src/components/Signup/Web2Signup.tsx
  front-end/src/components/Signup/Web3Signup.tsx
  front-end/src/ui-components/Form.tsx
Labels: PR-1-please review

#656 Api display error
  front-end/src/components/Post/GovernanceSideBar/Proposals/ProposalVoteInfo.tsx
  front-end/src/components/Post/GovernanceSideBar/Proposals/SecondProposal.tsx
  front-end/src/components/Post/GovernanceSideBar/Referenda/ReferendumVoteInfo.tsx
  front-end/src/components/Post/GovernanceSideBar/Referenda/VoteReferendum.tsx
  front-end/src/components/Post/GovernanceSideBar/VoteMotion.tsx
  front-end/src/ui-components/Form.tsx
  front-end/src/ui-components/Loader.tsx
Labels: PR-1-please review

#720 Added post id in update email
  auth-server/src/controllers/eventsHook.ts
  auth-server/src/services/email.ts
  auth-server/src/utils/getPostId.ts
  auth-server/src/utils/getPostLink.ts
Labels: x- changelog-feature

#734 Prevent a threshold wrongly placed when the api isn't loaded.
  front-end/src/ui-components/VoteProgress.tsx
Labels: x- changelog-fix
