Repository paritytech/polkassembly, pull requests merged in 2020-09, with the labels that each got.

#1018 Discussion Sort by feature
  front-end/src/generated/graphql.tsx
  front-end/src/global/sortOptions.ts
  front-end/src/screens/Discussions/Discussions.tsx
  front-end/src/screens/Discussions/index.tsx
  front-end/src/screens/Discussions/query.ts
Labels: PR-1-please review

#1022 Api bump v1.32.1
  auth-server/package.json
  auth-server/yarn.lock
  front-end/package.json
  front-end/yarn.lock
  health-monitor/package.json
  health-monitor/yarn.lock
  node-watcher/package.json
  node-watcher/yarn.lock
Labels: PR-1-please review

#1027 Bump api 1.33
  auth-server/package.json
  auth-server/yarn.lock
  front-end/package.json
  front-end/yarn.lock
  health-monitor/package.json
  health-monitor/yarn.lock
  node-watcher/package.json
  node-watcher/yarn.lock
Labels: x- changelog-chore

#1021 Add links to governance info rather than redirecting automatically
  front-end/src/components/ExternalLinks.tsx
  front-end/src/components/Post/Post.tsx
  front-end/src/hooks/index.ts
  front-end/src/hooks/useRedirectGovernancePost.ts
  front-end/src/screens/DiscussionPost/index.tsx
  front-end/src/screens/MotionPost/index.tsx
  front-end/src/screens/ProposalPost/index.tsx
  front-end/src/screens/TreasuryPost/index.tsx
Labels: PR-1-please review

#1028 Cleaner encode/decode without Keyring or Buffer
  auth-server/src/utils/getPublicKey.ts
  auth-server/src/utils/verifySignature.ts
  auth-server/test/resolvers/mutation/addressUnlinkKusama.spec.ts
  auth-server/test/resolvers/mutation/addressUnlinkPolkadot.spec.ts
  auth-server/test/utils/getPublicKey/getPublicKey.spec.ts
  front-end/src/util/getEncodedAddress.ts
Labels: PR-1-please review

#1034 Support any address crypto
  auth-server/src/utils/verifySignature.ts
Labels: PR-1-please review

#1035 Fix onchain referendum status filter Canceled -> Cancelled
  front-end/src/generated/graphql.tsx
  front-end/src/screens/OnChain/Referenda/query.ts
Labels: x- changelog-fix

#1036 Require node-forge ^0.10
  chain-db-open-server/package.json
  chain-db-open-server/yarn.lock
Labels: PR-1-please review

#1039 green red color for motion's method for approve reject proposal
  front-end/src/components/Post/PostGovernanceInfo/PostMotionInfo.tsx
Labels: x- changelog-feature
