Repository paritytech/polkassembly, pull requests merged in 2020-05, with the labels that each got.

#731 Automate draft release publication
  .gitlab-ci.yml
  .maintain/generate_changelog.sh
  .maintain/lib.sh
  .maintain/publish_draft_release.sh
Labels: x- changelog-feature

#746 Use local cluster nodewatcher server url for test environment
  kubernetes/polkassembly/values-dashboards-cluster-1.yaml
Labels: PR-2-insubstantial

#742 Fix overlapping title and status
  front-end/src/components/Post/PostContent.tsx
Labels: x- changelog-fix

#749 Set timeout 3s -> 30s
  front-end/src/components/Post/GovernanceSideBar/Proposals/ProposalVoteInfo.tsx
  front-end/src/components/Post/GovernanceSideBar/Referenda/ReferendumVoteInfo.tsx
Labels: x- changelog-fix

#744 Added refetch in useEffect to reload page on react navigation
  front-end/src/screens/Discussions/Discussions.tsx
  front-end/src/screens/Home/LatestDiscussions/index.tsx
  front-end/src/screens/Home/LatestMotions/index.tsx
  front-end/src/screens/Home/LatestProposals/index.tsx
  front-end/src/screens/Home/LatestReferenda/index.tsx
  front-end/src/screens/Home/LatestTreasury/index.tsx
  front-end/src/screens/OnChain/Motions/index.tsx
  front-end/src/screens/OnChain/Proposals/index.tsx
  front-end/src/screens/OnChain/Referenda/index.tsx
  front-end/src/screens/OnChain/Treasury/index.tsx
Labels: x- changelog-fix

#758 Delete unused `users` query from auth-server
  auth-server/src/resolvers/index.ts
  auth-server/src/resolvers/query/user.ts
  auth-server/src/resolvers/query/users.ts
  auth-server/src/schema/index.ts
  auth-server/src/schema/query/users.ts
  auth-server/src/schema/type/user.ts
  auth-server/src/services/auth.ts
  auth-server/src/types.ts
  auth-server/test/resolvers/query/users.spec.ts
Labels: x- changelog-fix

#748 Token as single source of truth
  auth-server/src/services/auth.ts
  auth-server/src/types.ts
  front-end/src/components/Apollo.tsx
  front-end/src/components/Login/Web2Login.tsx
  front-end/src/components/Login/Web3Login.tsx
  front-end/src/components/Signup/Web2Signup.tsx
  front-end/src/components/Signup/Web3Signup.tsx
  front-end/src/context/UserDetailsContext.tsx
  front-end/src/screens/NotificationSettings/index.tsx
  front-end/src/screens/Settings/address.tsx
  front-end/src/screens/Settings/email.tsx
  front-end/src/screens/Settings/fullname.tsx
  front-end/src/screens/Settings/setCredentials.tsx
  front-end/src/screens/Settings/username.tsx
  front-end/src/screens/UndoEmailChange/index.tsx
  front-end/src/screens/VerifyEmail/index.tsx
  front-end/src/services/auth.service.tsx
  front-end/src/types.ts
Labels: PR-1-please review

#737 Wider comment thread
  front-end/src/components/Post/GovernanceSideBar/Proposals/ProposalVoteInfo.tsx
  front-end/src/components/Post/GovernanceSideBar/Referenda/ReferendumVoteInfo.tsx
  front-end/src/components/Post/Post.tsx
  front-end/src/themes/theme.ts
  front-end/src/ui-components/AddressDropdown.tsx
  front-end/src/ui-components/Form.tsx
  front-end/src/ui-components/Input.tsx
Labels: x- changelog-feature

#683 Countdown component
  front-end/src/components/BlockCountdown.tsx
  front-end/src/components/BlocksToTime.tsx
  front-end/src/components/Post/GovernanceSideBar/index.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostReferendumInfo.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/global/networkConstants.ts
  front-end/src/screens/ReferendumPost/query.ts
  front-end/src/types.ts
  front-end/src/util/blockToTime.ts
Labels: x- changelog-feature

#753 Use apiPromise from @substrate/context
  front-end/package.json
  front-end/src/App.tsx
  front-end/src/components/Balance.tsx
  front-end/src/components/BlockCountdown.tsx
  front-end/src/components/BlocksToTime.tsx
  front-end/src/components/Post/GovernanceSideBar/Proposals/ProposalVoteInfo.tsx
  front-end/src/components/Post/GovernanceSideBar/Proposals/SecondProposal.tsx
  front-end/src/components/Post/GovernanceSideBar/Referenda/ReferendumVoteInfo.tsx
  front-end/src/components/Post/GovernanceSideBar/Referenda/VoteReferendum.tsx
  front-end/src/components/Post/GovernanceSideBar/VoteMotion.tsx
  front-end/src/components/Post/GovernanceSideBar/index.tsx
  front-end/src/context/ApiContext.tsx
  front-end/src/ui-components/Address.tsx
  front-end/yarn.lock
Labels: x- changelog-fix

#736 Tag styling fixes
  front-end/src/screens/CreatePost/TopicsRadio.tsx
  front-end/src/screens/CreatePost/index.tsx
  front-end/src/themes/theme.ts
  front-end/src/ui-components/InlineTag.tsx
  front-end/src/ui-components/StatusTag.tsx
Labels: PR-1-please review

#768 Fix to show the parent display name first
  front-end/src/ui-components/Address.tsx
Labels: PR-1-please review

#772 Voting Progress Bar overflow fix on small desktop width
  front-end/src/components/Post/Post.tsx
  front-end/src/ui-components/GlobalStyle.tsx
Labels: PR-1-please review

#777 fix ui glitches
  front-end/src/components/Comment/Comment.tsx
  front-end/src/components/Post/PostContent.tsx
  front-end/src/ui-components/Address.tsx
  front-end/src/ui-components/CreationLabel.tsx
  front-end/src/ui-components/NameLabel.tsx
  front-end/src/ui-components/UpdateLabel.tsx
Labels: x- changelog-fix

#769 Bump @polkadot deps
  auth-server/package.json
  auth-server/yarn.lock
  front-end/package.json
  front-end/src/components/Comment/Comment.tsx
  front-end/src/components/Comment/Comments.tsx
  front-end/yarn.lock
  util/package.json
  util/yarn.lock
Labels: x- changelog-fix

#697 Added health monitor
  auth-server/package.json
  chain-db-watcher/README.md
  chain-db-watcher/package.json
  chain-db-watcher/src/index.ts
  front-end/package.json
  health-monitor/.dockerignore
  health-monitor/.editorconfig
  health-monitor/.eslintignore
  health-monitor/.eslintrc.json
  health-monitor/.gitignore
  health-monitor/Dockerfile
  health-monitor/README.md
  health-monitor/package.json
  health-monitor/src/index.ts
  health-monitor/tsconfig.json
  health-monitor/yarn.lock
  kubernetes/polkassembly/values.yaml
Labels: PR-1-please review

#787 Remove unused notification schema
  auth-server/src/schema/index.ts
  auth-server/src/schema/query/notification.ts
Labels: x- changelog-fix

#780 Add identity check next to account's names
  front-end/src/ui-components/Address.tsx
  front-end/src/ui-components/IdentityBadge.tsx
Labels: PR-1-please review

#792 Sidebar glitch fix
  front-end/src/components/Post/GovernanceSideBar/Referenda/ReferendumVoteInfo.tsx
  front-end/src/components/Post/Post.tsx
  front-end/src/ui-components/GlobalStyle.tsx
Labels: x- changelog-fix

#798 Accept any interface for chain-db-watcher health
  chain-db-watcher/src/index.ts
Labels: x- changelog-fix

#774 Util unit tests
  front-end/jest.config.js
  front-end/package.json
  front-end/src/test/__snapshots__/storyshots.test.ts.snap
  front-end/src/util/__tests__/blockToTime.test.ts
  front-end/src/util/__tests__/formatBnBalance.test.ts
  front-end/src/util/__tests__/getEncodedAddress.test.ts
  front-end/src/util/__tests__/validation.test.ts
  front-end/src/util/blockToTime.ts
  front-end/src/util/formatBnBalance.ts
  front-end/yarn.lock
Labels: PR-1-please review

#778 Added check for unique address
  auth-server/src/resolvers/mutation/addressLinkStart.ts
  auth-server/src/utils/messages.ts
  auth-server/test/resolvers/mutation/addressLinkConfirm.spec.ts
  auth-server/test/resolvers/mutation/addressLinkStart.spec.ts
Labels: x- changelog-fix

#797 Setting first address as default
  auth-server/src/services/auth.ts
  auth-server/test/resolvers/mutation/addressLinkConfirm.spec.ts
Labels: x- changelog-fix

#793 Add info box for user with no default address
  front-end/src/components/DefaultAddressInfoBox.tsx
  front-end/src/screens/Discussions/index.tsx
  front-end/src/screens/Home/index.tsx
  front-end/src/themes/theme.ts
  front-end/src/ui-components/GlobalStyle.tsx
  front-end/src/ui-components/InfoBox.tsx
Labels: PR-1-please review

#801 Upgrade dependancies
  auth-server/package.json
  auth-server/yarn.lock
  chain-db-watcher/package.json
  chain-db-watcher/src/generated/chain-db-graphql.ts
  chain-db-watcher/src/generated/discussion-db-graphql.ts
  chain-db-watcher/yarn.lock
  front-end/package.json
  front-end/src/components/MenuBar/index.tsx
  front-end/src/ui-components/MarkdownEditor.tsx
  front-end/yarn.lock
  health-monitor/package.json
  health-monitor/yarn.lock
Labels: x- changelog-feature

#796 Fix and Feat for progress bar
  front-end/package.json
  front-end/src/components/Post/GovernanceSideBar/Referenda/ReferendumVoteInfo.tsx
  front-end/src/ui-components/PassingInfo.tsx
  front-end/src/ui-components/VoteProgress.tsx
  front-end/yarn.lock
Labels: x- changelog-feature

#785 removed user from login/signup response
  auth-server/src/resolvers/mutation/addressLogin.ts
  auth-server/src/resolvers/mutation/addressSignupConfirm.ts
  auth-server/src/resolvers/mutation/login.ts
  auth-server/src/resolvers/mutation/signup.ts
  auth-server/src/schema/index.ts
  auth-server/src/schema/query/notification.ts
  auth-server/src/schema/type/loginResponse.ts
  auth-server/src/services/auth.ts
  auth-server/src/types.ts
  auth-server/test/helpers.ts
  auth-server/test/resolvers/mutation/addressLinkConfirm.spec.ts
  auth-server/test/resolvers/mutation/addressLinkStart.spec.ts
  auth-server/test/resolvers/mutation/addressLogin.spec.ts
  auth-server/test/resolvers/mutation/addressSignup.spec.ts
  auth-server/test/resolvers/mutation/addressUnlink.spec.ts
  auth-server/test/resolvers/mutation/changeEmail.spec.ts
  auth-server/test/resolvers/mutation/changeName.spec.ts
  auth-server/test/resolvers/mutation/changeNotificationPreference.spec.ts
  auth-server/test/resolvers/mutation/changePassword.spec.ts
  auth-server/test/resolvers/mutation/changeUsername.spec.ts
  auth-server/test/resolvers/mutation/login.spec.ts
  auth-server/test/resolvers/mutation/logout.spec.ts
  auth-server/test/resolvers/mutation/postSubscribe.spec.ts
  auth-server/test/resolvers/mutation/postUnsubscribe.spec.ts
  auth-server/test/resolvers/mutation/resendVerifyEmailToken.spec.ts
  auth-server/test/resolvers/mutation/resetPassword.spec.ts
  auth-server/test/resolvers/mutation/signup.spec.ts
  auth-server/test/resolvers/mutation/undoEmailChange.spec.ts
  auth-server/test/resolvers/mutation/verifyEmail.spec.ts
  auth-server/test/resolvers/query/subscription.spec.ts
  front-end/src/components/Login/Web2Login.tsx
  front-end/src/components/Login/Web3Login.tsx
  front-end/src/components/Login/query.tsx
  front-end/src/components/Signup/Web2Signup.tsx
  front-end/src/components/Signup/query.ts
  front-end/src/generated/graphql.tsx
Labels: x- changelog-feature

#782 Moved email verify token to redis
  auth-server/src/model/EmailVerificationToken.ts
  auth-server/src/services/auth.ts
  auth-server/src/services/email.ts
  auth-server/src/utils/messages.ts
  auth-server/test/resolvers/mutation/changeEmail.spec.ts
  auth-server/test/resolvers/mutation/resendVerifyEmailToken.spec.ts
  auth-server/test/resolvers/mutation/verifyEmail.spec.ts
  auth-server/test/services/email/email.spec.ts
Labels: x- changelog-feature

#806 Add chore flag to changelog
  .maintain/generate_changelog.sh
Labels: x- changelog-feature

#809 Account link unlink refactoring
  front-end/src/screens/Settings/address.tsx
  front-end/src/types.ts
Labels: PR-1-please review

#784 Show linked addresses right away if anywithout prompting for accounts
  front-end/src/screens/Settings/address.tsx
  front-end/src/types.ts
Labels: PR-1-please review

#813 Fix vertical alignment of address, button and label in address settings
  front-end/src/screens/Settings/address.tsx
Labels: x- changelog-fix

#808 Bump @polkadot/api to 1.16
  auth-server/package.json
  auth-server/yarn.lock
  front-end/package.json
  front-end/src/components/Post/GovernanceSideBar/Proposals/ProposalVoteInfo.tsx
  front-end/src/components/Post/GovernanceSideBar/Proposals/SecondProposal.tsx
  front-end/src/components/Post/GovernanceSideBar/Proposals/index.tsx
  front-end/src/components/Post/GovernanceSideBar/index.tsx
  front-end/yarn.lock
  health-monitor/package.json
  health-monitor/yarn.lock
Labels: PR-1-please review

#815 Cancel poll vote interaction
  front-end/src/components/Post/Poll/GeneralSignals.tsx
  front-end/src/ui-components/AyeNayButtons.tsx
  front-end/src/ui-components/Form.tsx
  front-end/src/ui-components/GeneralChainSignalBar.tsx
Labels: PR-1-please review

#823 Fix threshold outside of screen
  front-end/src/ui-components/VoteProgress.tsx
Labels: PR-1-please review
