Repository paritytech/polkassembly, pull requests merged in 2020-03, with the labels that each got.

#411 Added notification control center
  auth-server/migrations/20200225193118_notification.js
  auth-server/src/model/Notification.ts
  auth-server/src/resolvers/index.ts
  auth-server/src/resolvers/mutation/changeNotificationPreference.ts
  auth-server/src/schema/index.ts
  auth-server/src/schema/mutation/changeNotificationPreference.ts
  auth-server/src/schema/type/notificationPreferencesType.ts
  auth-server/src/services/auth.ts
  auth-server/src/types.ts
  auth-server/src/utils/messages.ts
  auth-server/test/resolvers/mutation/changeNotificationPreference.spec.ts
Labels: PR-1-please review

#383 Notify user on create proposal
  auth-server/README.md
  auth-server/src/controllers/eventsHook.ts
  auth-server/src/controllers/subscriptionHook.ts
  auth-server/src/routes.ts
  auth-server/src/services/email.ts
  auth-server/src/utils/messages.ts
  chain-db-watcher/src/generated/chain-db-graphql.ts
  chain-db-watcher/src/generated/discussion-db-graphql.ts
  hasura/docker-compose.yaml.example
  hasura/hasura-migrations/migrations/1582534538758_delete_trigger_post_subscription/down.yaml
  hasura/hasura-migrations/migrations/1582534538758_delete_trigger_post_subscription/up.yaml
  hasura/hasura-migrations/migrations/1582534572909_create_trigger_comment_create/down.yaml
  hasura/hasura-migrations/migrations/1582534572909_create_trigger_comment_create/up.yaml
  hasura/hasura-migrations/migrations/1582547761965_create_trigger_onchain_link_create/down.yaml
  hasura/hasura-migrations/migrations/1582547761965_create_trigger_onchain_link_create/up.yaml
  kubernetes/polkassembly/auth-server-config.yaml
  kubernetes/polkassembly/auth-server-deployment.yaml
  kubernetes/polkassembly/hasura-config.yaml
  kubernetes/polkassembly/hasura-deployment.yaml
Labels: PR-6-got comments

#418 Niklabh feature notification control center front end
  auth-server/src/resolvers/index.ts
  auth-server/src/resolvers/query/notification.ts
  auth-server/src/schema/index.ts
  auth-server/src/schema/mutation/changeNotificationPreference.ts
  auth-server/src/schema/query/notification.ts
  auth-server/src/schema/type/notificationPreferences.ts
  auth-server/src/schema/type/notificationPreferencesInput.ts
  front-end/src/components/Post/PostCommentForm.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/screens/CreatePost/index.tsx
  front-end/src/screens/Settings/index.tsx
  front-end/src/screens/Settings/notification.tsx
  front-end/src/screens/Settings/query.ts
Labels: PR-6-got comments

#436 Styling inconsistencies + menu
  front-end/src/components/MenuBar/index.tsx
  front-end/src/components/Post/GovernanceSideBar/SecondProposal.tsx
  front-end/src/components/Post/GovernanceSideBar/VoteReferendum.tsx
  front-end/src/components/Post/GovernanceSideBar/index.tsx
  front-end/src/screens/Settings/address.tsx
  front-end/src/ui-components/Field.tsx
  front-end/src/ui-components/Form.tsx
Labels: PR-1-please review

#437 Front-end not launched in launch.sh
  launch.sh
Labels: PR-1-please review, PR-2-insubstantial

#432 Onchain Info Style Wrapper
  front-end/src/components/Post/PostGovernanceInfo/PostMotionInfo.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostProposalInfo.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostReferendumInfo.tsx
  front-end/src/ui-components/OnchainInfoWrapper.tsx
Labels: PR-1-please review

#442 Fix menu items
  front-end/src/components/MenuBar/index.tsx
Labels: PR-1-please review

#422 Added treasury spend proposal in chain db
  chain-db-watcher/README.md
  chain-db-watcher/src/generated/chain-db-graphql.ts
  chain-db-watcher/src/generated/discussion-db-graphql.ts
  chain-db-watcher/src/graphql_helpers.ts
  chain-db-watcher/src/index.ts
  chain-db-watcher/src/queries.ts
  chain-db-watcher/src/queries/discussions-db.queries.ts
  chain-db-watcher/src/sync/getter.ts
  chain-db-watcher/src/sync/index.ts
  chain-db-watcher/src/sync/queries/chain-db.queries.ts
  chain-db-watcher/src/sync/queries/discussions-db.queries.ts
  chain-db-watcher/src/sync/utils.ts
  chain-db-watcher/src/types.ts
  hasura/hasura-migrations/migrations/1582874306534_alter_table_public_onchain_links_add_column_onchain_treasury_proposal_id/down.yaml
  hasura/hasura-migrations/migrations/1582874306534_alter_table_public_onchain_links_add_column_onchain_treasury_proposal_id/up.yaml
  hasura/hasura-migrations/migrations/1582891815240_table_onchain_links_create_remote_relationship_onchain_treasury_spend_proposal/down.yaml
  hasura/hasura-migrations/migrations/1582891815240_table_onchain_links_create_remote_relationship_onchain_treasury_spend_proposal/up.yaml
  hasura/hasura-migrations/migrations/1583160765774_update_permission_proposal_bot_public_table_onchain_links/down.yaml
  hasura/hasura-migrations/migrations/1583160765774_update_permission_proposal_bot_public_table_onchain_links/up.yaml
  hasura/hasura-migrations/migrations/1583160772808_update_permission_anonymous_public_table_onchain_links/down.yaml
  hasura/hasura-migrations/migrations/1583160772808_update_permission_anonymous_public_table_onchain_links/up.yaml
  hasura/hasura-migrations/migrations/1583160780222_update_permission_user_public_table_onchain_links/down.yaml
  hasura/hasura-migrations/migrations/1583160780222_update_permission_user_public_table_onchain_links/up.yaml
  hasura/hasura-migrations/migrations/1583160793903_update_permission_proposal_bot_public_table_onchain_links/down.yaml
  hasura/hasura-migrations/migrations/1583160793903_update_permission_proposal_bot_public_table_onchain_links/up.yaml
  hasura/hasura-migrations/migrations/1583160911479_update_permission_proposal_bot_public_table_onchain_links/down.yaml
  hasura/hasura-migrations/migrations/1583160911479_update_permission_proposal_bot_public_table_onchain_links/up.yaml
  hasura/hasura-migrations/migrations/1583174810003_update_permission_proposal_bot_public_table_onchain_links/down.yaml
  hasura/hasura-migrations/migrations/1583174810003_update_permission_proposal_bot_public_table_onchain_links/up.yaml
  kubernetes/polkassembly/chain-db-watcher-config.yaml
  kubernetes/polkassembly/chain-db-watcher-deployment.yaml
Labels: PR-1-please review

#434 Added notification preferences to JWT
  auth-server/src/resolvers/index.ts
  auth-server/src/resolvers/mutation/changeNotificationPreference.ts
  auth-server/src/resolvers/query/notification.ts
  auth-server/src/schema/mutation/changeNotificationPreference.ts
  auth-server/src/services/auth.ts
  auth-server/src/types.ts
  auth-server/src/utils/getNotificationPreferencesFromUserId.ts
  front-end/src/App.tsx
  front-end/src/components/MenuBar/index.tsx
  front-end/src/components/Post/PostCommentForm.tsx
  front-end/src/context/UserDetailsContext.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/screens/CreatePost/index.tsx
  front-end/src/screens/NotificationSettings/index.tsx
  front-end/src/screens/NotificationSettings/query.ts
  front-end/src/screens/Settings/index.tsx
  front-end/src/screens/Settings/notification.tsx
  front-end/src/screens/Settings/query.ts
  front-end/src/types.ts
Labels: PR-1-please review

#462 Fix reset password
  front-end/src/screens/RequestResetPassword/index.tsx
Labels: PR-1-please review

#467 Remove everything, and add everything again, without typo
  hasura/hasura-migrations/migrations/1583343381115_table_onchain_links_drop_remote_relationship_onchain_referendum/down.yaml
  hasura/hasura-migrations/migrations/1583343381115_table_onchain_links_drop_remote_relationship_onchain_referendum/up.yaml
  hasura/hasura-migrations/migrations/1583343385618_table_onchain_links_drop_remote_relationship_onchain_motion/down.yaml
  hasura/hasura-migrations/migrations/1583343385618_table_onchain_links_drop_remote_relationship_onchain_motion/up.yaml
  hasura/hasura-migrations/migrations/1583343390568_table_onchain_links_drop_remote_relationship_onchain_proposal/down.yaml
  hasura/hasura-migrations/migrations/1583343390568_table_onchain_links_drop_remote_relationship_onchain_proposal/up.yaml
  hasura/hasura-migrations/migrations/1583343434377_table_onchain_links_drop_remote_relationship_onchain_treasury_spend_proposal/down.yaml
  hasura/hasura-migrations/migrations/1583343434377_table_onchain_links_drop_remote_relationship_onchain_treasury_spend_proposal/up.yaml
  hasura/hasura-migrations/migrations/1583343458805_remove_remote_schema_chain-db/down.yaml
  hasura/hasura-migrations/migrations/1583343458805_remove_remote_schema_chain-db/up.yaml
  hasura/hasura-migrations/migrations/1583343552059_create_remote_schema_chain-db/down.yaml
  hasura/hasura-migrations/migrations/1583343552059_create_remote_schema_chain-db/up.yaml
  hasura/hasura-migrations/migrations/1583343614940_table_onchain_links_create_remote_relationship_onchain_referendum/down.yaml
  hasura/hasura-migrations/migrations/1583343614940_table_onchain_links_create_remote_relationship_onchain_referendum/up.yaml
  hasura/hasura-migrations/migrations/1583343651816_table_onchain_links_create_remote_relationship_onchain_motion/down.yaml
  hasura/hasura-migrations/migrations/1583343651816_table_onchain_links_create_remote_relationship_onchain_motion/up.yaml
  hasura/hasura-migrations/migrations/1583343703170_table_onchain_links_create_remote_relationship_onchain_proposal/down.yaml
  hasura/hasura-migrations/migrations/1583343703170_table_onchain_links_create_remote_relationship_onchain_proposal/up.yaml
  hasura/hasura-migrations/migrations/1583343780587_table_onchain_links_create_remote_relationship_onchain_treasury_spend_proposal/down.yaml
  hasura/hasura-migrations/migrations/1583343780587_table_onchain_links_create_remote_relationship_onchain_treasury_spend_proposal/up.yaml
Labels: PR-1-please review

#489 No restart for docker test
  auth-server/docker-compose-test.yaml
Labels: PR-1-please review

#493 Set ip in migration for nodewatcher
  hasura/hasura-migrations/migrations/1578932276990_create_remote_schema_chain-db/up.yaml
Labels: PR-1-please review

#504 More referenda
  front-end/src/screens/OnChain/Motions/index.tsx
  front-end/src/screens/OnChain/Proposals/index.tsx
  front-end/src/screens/OnChain/Referenda/index.tsx
  front-end/src/screens/OnChain/Treasury/index.tsx
Labels: PR-1-please review

#463 Added new proposal email
  auth-server/src/controllers/eventsHook.ts
  auth-server/src/services/email.ts
  front-end/src/screens/NotificationSettings/index.tsx
  hasura/hasura-migrations/migrations/1583398528688_modify_tr_onchain_link_create_ops/down.yaml
  hasura/hasura-migrations/migrations/1583398528688_modify_tr_onchain_link_create_ops/up.yaml
Labels: PR-7-manual deployment

#511 Allowed special characters and emojis 🥇 in name
  auth-server/src/utils/messages.ts
  auth-server/src/utils/validateName.ts
  front-end/src/screens/SignupForm/index.tsx
  front-end/src/util/messages.ts
Labels: PR-1-please review

#522 Using validator for validating email
  auth-server/package.json
  auth-server/src/utils/validateEmail.ts
  auth-server/yarn.lock
Labels: PR-1-please review

#559 Upgrade eslint and polkadot api
  auth-server/package.json
  auth-server/yarn.lock
  chain-db-watcher/package.json
  chain-db-watcher/yarn.lock
  front-end/package.json
  front-end/yarn.lock
Labels: PR-1-please review

#561 Mark Tx status as valid when in block
  front-end/src/components/Post/GovernanceSideBar/SecondProposal.tsx
  front-end/src/components/Post/GovernanceSideBar/VoteMotion.tsx
  front-end/src/components/Post/GovernanceSideBar/VoteReferendum.tsx
Labels: PR-1-please review

#564 Enhanced loading status
  front-end/src/components/Post/GovernanceSideBar/SecondProposal.tsx
  front-end/src/components/Post/GovernanceSideBar/VoteMotion.tsx
  front-end/src/components/Post/GovernanceSideBar/VoteReferendum.tsx
  front-end/src/types.ts
Labels: PR-1-please review

#569 Reactions styling
  front-end/src/components/Comment/Comment.tsx
  front-end/src/components/Comment/EditableCommentContent.tsx
  front-end/src/components/Post/Post.tsx
  front-end/src/components/Reactionbar/index.tsx
  front-end/src/themes/theme.ts
  front-end/src/ui-components/Avatar.tsx
  front-end/src/ui-components/Button.tsx
  front-end/src/ui-components/CreationLabel.tsx
Labels: PR-1-please review

#579 Use one refecth function without variables
  front-end/src/components/Reactionbar/CommentReactionBar.tsx
  front-end/src/components/Reactionbar/PostReactionBar.tsx
  front-end/src/components/Reactionbar/ReactionButton.tsx
Labels: PR-1-please review

#586 api 1.8.1 and refactoring of governance info
  front-end/package.json
  front-end/src/components/Post/GovernanceSideBar/Proposals/ProposalVoteInfo.tsx
  front-end/src/components/Post/GovernanceSideBar/Proposals/SecondProposal.tsx
  front-end/src/components/Post/GovernanceSideBar/Referenda/ReferendumVoteInfo.tsx
  front-end/src/components/Post/GovernanceSideBar/Referenda/VoteReferendum.tsx
  front-end/src/components/Post/GovernanceSideBar/VoteMotion.tsx
  front-end/src/components/Post/GovernanceSideBar/index.tsx
  front-end/src/ui-components/AccountSelectionForm.tsx
  front-end/src/ui-components/AyeNayButtons.tsx
  front-end/src/ui-components/BalanceInput.tsx
  front-end/yarn.lock
Labels: PR-1-please review

#566 Added seconds and votes in proposal/referendum governance side bar
  front-end/package.json
  front-end/src/components/Post/GovernanceSideBar/Proposals/ProposalVoteInfo.tsx
  front-end/src/components/Post/GovernanceSideBar/Proposals/SecondProposal.tsx
  front-end/src/components/Post/GovernanceSideBar/Referenda/ReferendumVoteInfo.tsx
  front-end/src/components/Post/GovernanceSideBar/Referenda/VoteReferendum.tsx
  front-end/src/components/Post/GovernanceSideBar/VoteMotion.tsx
  front-end/src/components/Post/GovernanceSideBar/index.tsx
  front-end/src/ui-components/AccountSelectionForm.tsx
  front-end/src/ui-components/AyeNayButtons.tsx
  front-end/src/ui-components/BalanceInput.tsx
  front-end/yarn.lock
Labels: PR-3-in progress
