Repository paritytech/polkassembly, pull requests merged in 2020-06, with the labels that each got.

#818 Add prisma to launch script
  launch.sh
  node-watcher/package.json
Labels: x- changelog-chore

#827 Added logs for hooks and email to debug email not being sent
  auth-server/src/controllers/eventsHook.ts
  auth-server/src/services/email.ts
Labels: x- changelog-chore

#819 Email Fixes
  auth-server/package.json
  auth-server/src/services/email.ts
  auth-server/src/utils/emailTemplates.ts
  auth-server/yarn.lock
Labels: x- changelog-fix

#828 Document remote migration for hasura
  hasura/README.md
Labels: x- changelog-chore

#830 Remove unused REACT_APP_ENV
  front-end/Dockerfile
  front-end/README.md
Labels: PR-1-please review

#832 Add polkadot tests in auth-server
  auth-server/test/resolvers/mutation/addressLinkConfirm.spec.ts
  auth-server/test/resolvers/mutation/addressLinkStartKusama.spec.ts
  auth-server/test/resolvers/mutation/addressLinkStartPolkadot.spec.ts
  auth-server/test/resolvers/mutation/addressLoginKusama.spec.ts
  auth-server/test/resolvers/mutation/addressLoginPolkadot.spec.ts
  auth-server/test/resolvers/mutation/addressSignupKusama.spec.ts
  auth-server/test/resolvers/mutation/addressSignupPolkadot.spec.ts
  auth-server/test/resolvers/mutation/addressUnlinkKusama.spec.ts
  auth-server/test/resolvers/mutation/addressUnlinkPolkadot.spec.ts
Labels: x- changelog-chore

#829 Create node-watcher harvester job
  node-watcher/kubernetes/node-watcher-harvester.yaml
Labels: PR-1-please review

#835 Move app name to global const instead of env variable
  front-end/Dockerfile
  front-end/README.md
  front-end/src/components/Login/Web3Login.tsx
  front-end/src/components/Post/GovernanceSideBar/index.tsx
  front-end/src/components/Signup/Web3Signup.tsx
  front-end/src/global/appName.ts
  front-end/src/screens/Settings/address.tsx
  front-end/src/screens/Settings/setCredentials.tsx
Labels: x- changelog-chore

#837 Fix non null exception
  front-end/src/screens/CreatePost/index.tsx
Labels: x- changelog-fix

#833 Use network getter on front end
  front-end/src/App.tsx
  front-end/src/assets/privacy-policy.ts
  front-end/src/assets/terms-and-conditions.ts
  front-end/src/components/ReportButton/index.tsx
  front-end/src/components/Signup/Web3Signup.tsx
  front-end/src/screens/Discussions/index.tsx
  front-end/src/services/auth.service.tsx
  front-end/src/util/getNetwork.ts
Labels: x- changelog-chore

#824 Added anchor to comments
  auth-server/src/controllers/eventsHook.ts
  auth-server/src/types.ts
  auth-server/src/utils/getPostCommentLink.ts
  front-end/src/components/Comment/Comment.tsx
  front-end/src/components/Comment/Comments.tsx
  front-end/src/components/Comment/EditableCommentContent.tsx
  front-end/src/components/Footer/index.tsx
  front-end/src/components/Post/Post.tsx
  front-end/src/util/copyToClipboard.ts
Labels: x- changelog-feature

#841 Add dropdown menu to switch network
  front-end/src/assets/kusama-logo.gif
  front-end/src/assets/polkadot-logo.svg
  front-end/src/components/MenuBar/index.tsx
  front-end/src/ui-components/NetworkDropdown.tsx
Labels: x- changelog-feature

#840 Remove non secret variables from Gitlab
  .gitlab-ci.yml
  front-end/Dockerfile
  kubernetes/polkassembly/values.yaml
Labels: x- changelog-chore

#844 Markdown target _blank for opening link in new tab
  front-end/src/ui-components/Markdown.tsx
Labels: x- changelog-fix

#853 Fix icon for failing referendum
  front-end/src/ui-components/PassingInfo.tsx
Labels: PR-1-please review

#855 Verify all needed env vars at launch and print any missing one.
  chain-db-watcher/src/index.ts
Labels: x- changelog-feature

#852 Dynamic go-to-top button
  front-end/src/components/Comment/Comment.tsx
  front-end/src/components/Comment/Comments.tsx
  front-end/src/components/Footer/index.tsx
  front-end/src/components/Post/Post.tsx
  front-end/src/ui-components/ScrollToTop.tsx
Labels: x- changelog-fix

#857 Add production connection db
  auth-server/knexfile.ts
Labels: x- changelog-fix

#854 Use box-shadows on all card-like elements
  front-end/src/components/Comment/Comment.tsx
  front-end/src/components/DiscussionCard.tsx
  front-end/src/components/GovernanceCard.tsx
  front-end/src/components/Post/Post.tsx
  front-end/src/components/Post/PostCommentForm.tsx
  front-end/src/components/Reactionbar/CommentReactionBar.tsx
  front-end/src/components/Reactionbar/PostReactionBar.tsx
  front-end/src/screens/LegalDocuments/index.tsx
  front-end/src/screens/NotificationSettings/index.tsx
  front-end/src/screens/Settings/index.tsx
  front-end/src/themes/theme.ts
  front-end/src/ui-components/Button.tsx
  front-end/src/ui-components/Form.tsx
  front-end/src/ui-components/InfoBox.tsx
  front-end/src/ui-components/PassingInfo.tsx
Labels: x- changelog-chore

#858 Use account component in preimage arguments
  front-end/src/components/Post/PostGovernanceInfo/PostMotionInfo.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostProposalInfo.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostReferendumInfo.tsx
Labels: x- changelog-feature

#861 Remove setter for HASURA_CHAIN_DB_REMOTE_SCHEMA
  .gitlab-ci.yml
Labels: x- changelog-chore

#843 Make a "Cleared" proposal for the case democracy.clearProposal is called
  front-end/src/global/statuses.ts
  front-end/src/ui-components/StatusTag.tsx
  node-watcher/package.json
  node-watcher/src/tasks/createProposalStatus.ts
  node-watcher/src/tasks/createReferendumStatus.ts
  node-watcher/src/util/newProposalStatus.ts
  node-watcher/src/util/statuses.ts
Labels: x- changelog-fix

#860 Update @polkadot deps
  auth-server/package.json
  auth-server/test/resolvers/mutation/addressLinkConfirm.spec.ts
  auth-server/test/resolvers/mutation/addressLoginKusama.spec.ts
  auth-server/test/resolvers/mutation/addressLoginPolkadot.spec.ts
  auth-server/test/resolvers/mutation/addressSignupKusama.spec.ts
  auth-server/test/resolvers/mutation/addressSignupPolkadot.spec.ts
  auth-server/yarn.lock
  front-end/package.json
  front-end/src/components/Post/GovernanceSideBar/Referenda/ReferendumVoteInfo.tsx
  front-end/yarn.lock
  health-monitor/package.json
  health-monitor/yarn.lock
  launch.sh
  node-watcher/package.json
  node-watcher/yarn.lock
Labels: PR-1-please review

#866 Fix styled components warnings
  front-end/src/ui-components/IdentityBadge.tsx
Labels: x- changelog-fix

#863 Update node-watcher-hasvester job with latest changes
  kubernetes/node-watcher/node-watcher-harvester.yaml
  node-watcher/package.json
Labels: x- changelog-chore

#868 Add info about CI variables in Kubernetes readme
  kubernetes/README.md
Labels: x- changelog-chore

#874 Add a .yarnrc to set 10min timeout for package retrieval
  auth-server/.yarnrc
  chain-db-open-server/.yarnrc
  chain-db-watcher/.yarnrc
  front-end/.yarnrc
  health-monitor/.yarnrc
  node-watcher/.yarnrc
Labels: x- changelog-chore

#876 Print public env and warn about unset ones
  auth-server/src/index.ts
  auth-server/src/utils/verifyEnvVariables.ts
Labels: PR-1-please review

#864 Upgrade deps on front-end
  front-end/package.json
  front-end/src/components/Apollo.tsx
  front-end/src/components/ContentForm.tsx
  front-end/src/components/Post/GovernanceSideBar/Referenda/ReferendumVoteInfo.tsx
  front-end/src/components/TitleForm.tsx
  front-end/src/ui-components/AddressDropdown.tsx
  front-end/src/ui-components/MarkdownEditor.tsx
  front-end/src/ui-components/NetworkDropdown.tsx
  front-end/src/util/blockToTime.ts
  front-end/src/util/copyToClipboard.ts
  front-end/yarn.lock
Labels: x- changelog-chore

#869 Restyled scroll-to-top button
  front-end/src/ui-components/ScrollToTop.tsx
Labels: x- changelog-fix

#875 Set secure flag for cookie
  auth-server/src/utils/setRefreshTokenCookie.ts
Labels: x- changelog-chore

#862 Upgrade deps to address security alerts
  chain-db-open-server/package.json
  chain-db-open-server/src/index.ts
  chain-db-open-server/yarn.lock
  kubernetes/node-watcher/node-watcher-harvester.yaml
  node-watcher/package.json
Labels: x- changelog-chore

#870 Make sure emails are sent to all users willing to be notified
  auth-server/src/controllers/eventsHook.ts
  auth-server/src/services/auth.ts
  auth-server/src/services/email.ts
  auth-server/src/types.ts
  auth-server/src/utils/getPublicKey.ts
  auth-server/test/resolvers/mutation/addressLinkStartPolkadot.spec.ts
Labels: x- changelog-fix

#872 Removed display name
  auth-server/migrations/20200609211518_remove_name.js
  auth-server/src/model/User.ts
  auth-server/src/resolvers/index.ts
  auth-server/src/resolvers/mutation/changeName.ts
  auth-server/src/resolvers/mutation/reportContent.ts
  auth-server/src/resolvers/mutation/signup.ts
  auth-server/src/resolvers/query/user.ts
  auth-server/src/schema/index.ts
  auth-server/src/schema/mutation/changeName.ts
  auth-server/src/schema/mutation/signup.ts
  auth-server/src/schema/type/publicUser.ts
  auth-server/src/schema/type/user.ts
  auth-server/src/services/auth.ts
  auth-server/src/services/email.ts
  auth-server/src/types.ts
  auth-server/src/utils/messages.ts
  auth-server/src/utils/validateName.ts
  auth-server/test/helpers.ts
  auth-server/test/resolvers/mutation/addressLinkConfirm.spec.ts
  auth-server/test/resolvers/mutation/addressLinkStartKusama.spec.ts
  auth-server/test/resolvers/mutation/addressLinkStartPolkadot.spec.ts
  auth-server/test/resolvers/mutation/addressLoginKusama.spec.ts
  auth-server/test/resolvers/mutation/addressLoginPolkadot.spec.ts
  auth-server/test/resolvers/mutation/addressUnlinkKusama.spec.ts
  auth-server/test/resolvers/mutation/addressUnlinkPolkadot.spec.ts
  auth-server/test/resolvers/mutation/changeEmail.spec.ts
  auth-server/test/resolvers/mutation/changeName.spec.ts
  auth-server/test/resolvers/mutation/changeNotificationPreference.spec.ts
  auth-server/test/resolvers/mutation/changePassword.spec.ts
  auth-server/test/resolvers/mutation/changeUsername.spec.ts
  auth-server/test/resolvers/mutation/login.spec.ts
  auth-server/test/resolvers/mutation/logout.spec.ts
  auth-server/test/resolvers/mutation/postSubscribe.spec.ts
  auth-server/test/resolvers/mutation/postUnsubscribe.spec.ts
  auth-server/test/resolvers/mutation/resendVerifyEmailToken.spec.ts
  auth-server/test/resolvers/mutation/resetPassword.spec.ts
  auth-server/test/resolvers/mutation/signup.spec.ts
  auth-server/test/resolvers/mutation/undoEmailChange.spec.ts
  auth-server/test/resolvers/mutation/verifyEmail.spec.ts
  auth-server/test/resolvers/query/subscription.spec.ts
  auth-server/test/resolvers/query/user.spec.ts
  auth-server/test/services/email/email.spec.ts
  auth-server/test/utils/validateName/ValidateName.spec.ts
  front-end/src/components/Signup/Web2Signup.tsx
  front-end/src/components/Signup/query.ts
  front-end/src/context/UserDetailsContext.tsx
  front-end/src/fragments/author.ts
  front-end/src/generated/graphql.tsx
  front-end/src/screens/Settings/fullname.tsx
  front-end/src/screens/Settings/index.tsx
  front-end/src/screens/Settings/query.ts
  front-end/src/services/auth.service.tsx
  front-end/src/types.ts
  front-end/src/util/messages.ts
  front-end/src/util/validation.ts
Labels: x- changelog-chore

#883 Added better default content for onchain post
  chain-db-watcher/src/graphql_helpers.ts
Labels: x- changelog-chore

#886 Update hasura image
  hasura/docker-compose.yaml.example
  kubernetes/polkassembly/values.yaml
Labels: x- changelog-chore

#887 Added sub-category links to on-chain overview page
  front-end/src/screens/OnChain/index.tsx
Labels: x- changelog-feature

#888 Update to react-mde 10.1
  front-end/package.json
  front-end/yarn.lock
Labels: x- changelog-fix

#890 Remove no-extra-parens from eslint rules
  auth-server/.eslintrc.json
  chain-db-watcher/.eslintrc.json
  front-end/.eslintrc.json
  front-end/src/components/Post/GovernanceSideBar/Proposals/SecondProposal.tsx
  front-end/src/components/Post/GovernanceSideBar/index.tsx
  front-end/src/components/Post/Post.tsx
  front-end/src/hooks/useRedirectGovernancePost.ts
  health-monitor/.eslintrc.json
  util/.eslintrc.json
Labels: x- changelog-chore

#889 Remove hack seconding
  front-end/src/components/Post/GovernanceSideBar/Proposals/SecondProposal.tsx
Labels: x- changelog-chore

#892 This fixes a broken url in emails
  auth-server/src/utils/emailTemplates.ts
Labels: x- changelog-fix

#895 Fix typo in standard description
  chain-db-watcher/src/graphql_helpers.ts
Labels: PR-1-please review

#893 Mde-preview overlap fix when displaying code
  front-end/src/components/Comment/Comment.tsx
  front-end/src/components/Post/PostCommentForm.tsx
  front-end/src/ui-components/GlobalStyle.tsx
  front-end/src/ui-components/Markdown.tsx
Labels: x- changelog-fix

#904 Remove yarnrc
  auth-server/.yarnrc
  chain-db-open-server/.yarnrc
  chain-db-watcher/.yarnrc
  front-end/.yarnrc
  health-monitor/.yarnrc
  node-watcher/.yarnrc
Labels: PR-1-please review

#897 Keep title and buttons consistent
  front-end/src/components/DefaultAddressInfoBox.tsx
  front-end/src/components/Footer/index.tsx
  front-end/src/components/Login/Web2Login.tsx
  front-end/src/components/Login/Web3Login.tsx
  front-end/src/components/MenuBar/index.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostMotionInfo.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostProposalInfo.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostReferendumInfo.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostTreasuryInfo.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/screens/CreatePost/index.tsx
  front-end/src/screens/Discussions/index.tsx
  front-end/src/screens/Home/index.tsx
  front-end/src/screens/OnChain/index.tsx
  front-end/src/screens/Settings/address.tsx
  front-end/src/screens/Settings/setCredentials.tsx
Labels: x- changelog-chore

#913 Remove resolutions and change to use node on start
  chain-db-open-server/package.json
  chain-db-open-server/yarn.lock
Labels: x- changelog-fix

#909 Make on-chain screen concise
  front-end/src/components/Listings/MotionsListing.tsx
  front-end/src/components/Listings/ProposalsListing.tsx
  front-end/src/components/Listings/ReferendaListing.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/screens/OnChain/Motions/query.ts
  front-end/src/screens/OnChain/Proposals/query.ts
  front-end/src/screens/OnChain/Referenda/query.ts
  front-end/src/screens/OnChain/index.tsx
Labels: x- changelog-feature

#916 Remove some more resolutions in open server.
  chain-db-open-server/package.json
  chain-db-open-server/yarn.lock
Labels: PR-1-please review, x- changelog-fix

#917 Change pullPolicy for always open-server and node-watcher
  kubernetes/node-watcher/values.yaml
Labels: PR-1-please review

#896 Sort discussion by last update
  front-end/src/components/Listings/DiscussionsListing.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/screens/Discussions/query.ts
  hasura/hasura-migrations/migrations/1591974115375_run_sql_migration/down.yaml
  hasura/hasura-migrations/migrations/1591974115375_run_sql_migration/up.yaml
  hasura/hasura-migrations/migrations/1591974154804_create_relationship_post_public_table_post_last_update/down.yaml
  hasura/hasura-migrations/migrations/1591974154804_create_relationship_post_public_table_post_last_update/up.yaml
  hasura/hasura-migrations/migrations/1591974175368_update_permission_anonymous_public_table_post_last_update/down.yaml
  hasura/hasura-migrations/migrations/1591974175368_update_permission_anonymous_public_table_post_last_update/up.yaml
  hasura/hasura-migrations/migrations/1591974197981_update_permission_user_public_table_post_last_update/down.yaml
  hasura/hasura-migrations/migrations/1591974197981_update_permission_user_public_table_post_last_update/up.yaml
  hasura/hasura-migrations/migrations/1592305332830_drop_relationship_post_public_table_post_last_update/down.yaml
  hasura/hasura-migrations/migrations/1592305332830_drop_relationship_post_public_table_post_last_update/up.yaml
  hasura/hasura-migrations/migrations/1592305755095_create_relationship_last_update_public_table_posts/down.yaml
  hasura/hasura-migrations/migrations/1592305755095_create_relationship_last_update_public_table_posts/up.yaml
  launch.sh
Labels: x- changelog-feature

#900 Showing sidebar in mobile
  front-end/src/components/ExtensionNotDetected.tsx
  front-end/src/components/Post/Post.tsx
Labels: PR-1-please review

#920 Bump polkadot/api v1.19
  auth-server/package.json
  auth-server/yarn.lock
  front-end/package.json
  front-end/yarn.lock
  health-monitor/package.json
  health-monitor/yarn.lock
  node-watcher/package.json
  node-watcher/yarn.lock
Labels: PR-1-please review

#924 Use the new open-server-service in prod
  hasura/docker-compose.yaml.example
  kubernetes/polkassembly/values-dashboards-cluster-1.yaml
  kubernetes/polkassembly/values-parity-prod.yaml
  kubernetes/polkassembly/values.yaml
Labels: x- changelog-chore

#921 Add unique keys for polls and reactions
  hasura/hasura-migrations/migrations/1592400318046_alter_table_public_poll_votes_add_unique_poll_id_user_id/down.yaml
  hasura/hasura-migrations/migrations/1592400318046_alter_table_public_poll_votes_add_unique_poll_id_user_id/up.yaml
  hasura/hasura-migrations/migrations/1592400359607_alter_table_public_comment_reactions_add_unique_comment_id_user_id_reaction/down.yaml
  hasura/hasura-migrations/migrations/1592400359607_alter_table_public_comment_reactions_add_unique_comment_id_user_id_reaction/up.yaml
  hasura/hasura-migrations/migrations/1592400398659_alter_table_public_post_reactions_add_unique_post_id_user_id_reaction/down.yaml
  hasura/hasura-migrations/migrations/1592400398659_alter_table_public_post_reactions_add_unique_post_id_user_id_reaction/up.yaml
Labels: PR-2-on ice, x- changelog-fix

#923 Use hasura image v1.3.0-beta.2
  hasura/docker-compose.yaml.example
  kubernetes/polkassembly/values.yaml
Labels: x- changelog-chore

#927 Use new open server for node watcher and health monitor in prod
  kubernetes/polkassembly/values-parity-prod.yaml
Labels: PR-2-on ice, x- changelog-chore

#940 Print env and adjust values
  kubernetes/node-watcher/values-dashboards-cluster-1.yaml
  kubernetes/node-watcher/values-parity-prod.yaml
  kubernetes/node-watcher/values-polkadot-prod.yaml
  kubernetes/node-watcher/values.yaml
  kubernetes/polkassembly/values-polkadot-prod.yaml
  node-watcher/package.json
  node-watcher/src/index.ts
  node-watcher/src/nodeWatcher.ts
  node-watcher/src/util/getEnvVars.ts
Labels: x- changelog-chore

#929 Fix motion proposal info padding
  front-end/src/components/Post/PostGovernanceInfo/PostMotionInfo.tsx
Labels: PR-1-please review

#781 OG meta tags in head for social media sharing
  front-end/package.json
  front-end/src/App.tsx
  front-end/src/components/Head.tsx
  front-end/src/components/Post/Post.tsx
  front-end/src/context/MetaContext.tsx
  front-end/src/types.ts
  front-end/yarn.lock
Labels: x- changelog-feature

#941 Fix address encoding
  front-end/src/global/networkConstants.ts
  front-end/src/util/getEncodedAddress.ts
Labels: PR-1-please review

#926 Firing verify email mutation only once after landing on verify link
  front-end/src/screens/VerifyEmail/index.tsx
Labels: x- changelog-fix

#928 Uncomment chain-db check in healthmonitor now that it is in prod
  health-monitor/src/index.ts
Labels: x- changelog-chore

#831 Support Polkadot
  front-end/README.md
  front-end/src/components/MenuBar/index.tsx
Labels: x- changelog-feature

#943 Fix CI pipeline for Kusama prod (named parity-prod)
  kubernetes/redis/values/parity-prod.yaml
Labels: PR-1-please review

#944 Bump @polkadot deps to 0.20.1
  auth-server/package.json
  auth-server/yarn.lock
  front-end/package.json
  front-end/yarn.lock
  health-monitor/package.json
  health-monitor/yarn.lock
  node-watcher/package.json
  node-watcher/yarn.lock
Labels: PR-1-please review

#948 Set amount of replica for open-server to 1
  chain-db-open-server/kubernetes/server-deployment.yaml
  kubernetes/node-watcher/values.yaml
Labels: x- changelog-chore

#949 Bum polkadot deps to 1.22
  auth-server/package.json
  auth-server/yarn.lock
  front-end/package.json
  front-end/yarn.lock
  node-watcher/package.json
  node-watcher/yarn.lock
Labels: x- changelog-chore
