Repository paritytech/polkassembly, pull requests merged in 2020-08, with the labels that each got.

#977 Added extend poll feature
  front-end/src/components/Post/Poll/GeneralSignals.tsx
  front-end/src/components/Post/Poll/Poll.tsx
  front-end/src/components/Post/Poll/index.tsx
  front-end/src/components/Post/Poll/query.ts
  front-end/src/components/Post/Post.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/hooks/index.ts
  front-end/src/hooks/usePollEndBlock.ts
  front-end/src/screens/CreatePost/index.tsx
Labels: x- changelog-feature

#979 Showing last comment
  front-end/src/components/DiscussionCard.tsx
  front-end/src/components/Listings/DiscussionsListing.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/screens/Discussions/query.ts
Labels: x- changelog-feature

#978 Added remaining time on referenda listing
  front-end/src/components/BlockCountdown.tsx
  front-end/src/components/GovernanceCard.tsx
  front-end/src/components/Listings/ReferendaListing.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/screens/OnChain/Referenda/query.ts
  front-end/src/screens/Referenda/ReferendaContainer/query.ts
Labels: x- changelog-feature

#982 Added validate password function
  auth-server/src/resolvers/mutation/changePassword.ts
  auth-server/src/resolvers/mutation/resetPassword.ts
  auth-server/src/resolvers/mutation/setCredentialsConfirm.ts
  auth-server/src/resolvers/mutation/signup.ts
  auth-server/src/utils/validatePassword.ts
Labels: x- changelog-chore

#983 sending username in password reset email
  auth-server/src/services/email.ts
  auth-server/src/utils/emailTemplates.ts
  front-end/src/components/Login/Web2Login.tsx
Labels: x- changelog-feature

#986 Fix ended countdown
  front-end/src/components/GovernanceCard.tsx
Labels: x- changelog-fix

#984 Added delete comment feature
  front-end/src/components/Comment/EditableCommentContent.tsx
  front-end/src/components/Comment/query.ts
  front-end/src/generated/graphql.tsx
  hasura/hasura-migrations/metadata/tables.yaml
Labels: x- changelog-feature

#985 Added pagination
  front-end/src/generated/graphql.tsx
  front-end/src/screens/Discussions/Discussions.tsx
  front-end/src/screens/Motions/MotionsContainer/index.tsx
  front-end/src/screens/Proposals/ProposalsContainer/index.tsx
  front-end/src/screens/Referenda/ReferendaContainer/index.tsx
  front-end/src/screens/Tips/TipContainer/index.tsx
  front-end/src/screens/Treasury/TreasuryContainer/index.tsx
  front-end/src/ui-components/LoadMore.tsx
Labels: PR-1-please review

#990 Added load more spinner
  front-end/src/ui-components/LoadMore.tsx
Labels: PR-1-please review

#991 Made tip status more readable
  front-end/src/global/statuses.ts
  front-end/src/ui-components/StatusTag.tsx
Labels: x- changelog-fix

#992 Added dropdown menu for on chain item in mobile view
  front-end/src/components/MenuBar/index.tsx
  front-end/src/screens/Home/index.tsx
Labels: x- changelog-fix

#993 Go back to previous page after login signup
  front-end/src/components/Login/Web2Login.tsx
  front-end/src/components/Login/Web3Login.tsx
  front-end/src/components/Signup/Web2Signup.tsx
  front-end/src/components/Signup/Web3Signup.tsx
Labels: x- changelog-fix

#994 Highlighting own post/proposals with pink border
  front-end/src/components/DiscussionCard.tsx
  front-end/src/components/GovernanceCard.tsx
Labels: PR-1-please review

#997 Bump to api 1.28
  auth-server/package.json
  auth-server/yarn.lock
  front-end/package.json
  front-end/yarn.lock
  health-monitor/package.json
  health-monitor/yarn.lock
  node-watcher/package.json
  node-watcher/yarn.lock
Labels: x- changelog-chore

#995 Added council member label for council address
  front-end/src/ui-components/Address.tsx
  front-end/src/ui-components/IdentityBadge.tsx
Labels: x- changelog-feature

#1000 API bump 1.29.1
  auth-server/package.json
  auth-server/yarn.lock
  front-end/package.json
  front-end/yarn.lock
  health-monitor/package.json
  health-monitor/yarn.lock
  node-watcher/package.json
  node-watcher/yarn.lock
Labels: PR-1-please review

#1001 Added support for tagging users
  auth-server/src/controllers/eventsHook.ts
  auth-server/src/services/email.ts
  auth-server/src/utils/emailTemplates.ts
  auth-server/src/utils/getUserFromUsername.ts
  front-end/src/components/ContentForm.tsx
  front-end/src/components/Post/Post.tsx
  front-end/src/ui-components/MarkdownEditor.tsx
Labels: PR-1-please review

#1008 Api bump 1.30.1
  auth-server/package.json
  auth-server/yarn.lock
  front-end/package.json
  front-end/yarn.lock
  health-monitor/package.json
  health-monitor/yarn.lock
  node-watcher/package.json
  node-watcher/yarn.lock
Labels: PR-1-please review, x- changelog-chore

#1016 Added council votes info for motions
  front-end/src/components/Post/GovernanceSideBar/Motions/MotionVoteInfo.tsx
  front-end/src/components/Post/GovernanceSideBar/Motions/VoteMotion.tsx
  front-end/src/components/Post/GovernanceSideBar/index.tsx
  front-end/src/components/Post/Poll/CouncilSignals.tsx
  front-end/src/types.ts
Labels: PR-1-please review, x- changelog-feature
