Repository paritytech/polkassembly, pull requests merged in 2020-02, with the labels that each got.

#272 Yarn lock nits
  front-end/yarn.lock
Labels: PR-2-insubstantial

#281 Update README.md
  hasura/README.md
Labels: PR-1-please review, i-5-documentation

#284 Allow proposal / referendum edit
  front-end/src/components/Post/Post.tsx
Labels: PR-1-please review

#265 User can votes on proposal
  front-end/README.md
  front-end/package.json
  front-end/src/components/Post/Democracy.tsx
  front-end/src/components/Post/Post.tsx
  front-end/src/components/Post/SecondProposal.tsx
  front-end/src/components/Post/VoteRefrendum.tsx
  front-end/src/screens/Home/HomeContent.tsx
  front-end/src/screens/Settings/address.tsx
  front-end/yarn.lock
Labels: PR-1-please review

#303 Fv build args in dockerize
  .gitlab-ci.yml
  front-end/Dockerfile
Labels: PR-1-please review

#301 Opening polkadot extesion popup only on button click and not automatically
  front-end/src/screens/Settings/address.tsx
Labels: PR-1-please review

#313 Simple comment avatar
  front-end/src/components/Comment/Comment.tsx
  front-end/src/ui-components/Avatar.tsx
Labels: PR-1-please review

#312 Vote lock styling
  front-end/src/components/DiscussionCard.tsx
  front-end/src/components/GovernanceCard.tsx
  front-end/src/components/Post/VoteRefrendum.tsx
  front-end/src/themes/theme.ts
  front-end/src/ui-components/Button.tsx
  front-end/src/ui-components/Form.tsx
  front-end/src/ui-components/GlobalStyle.tsx
Labels: PR-1-please review

#309 Explanation boxes
  front-end/src/components/Listings/DiscussionsListing.tsx
  front-end/src/components/Listings/ProposalsListing.tsx
  front-end/src/components/Listings/ReferendaListing.tsx
  front-end/src/components/Post/VoteRefrendum.tsx
  front-end/src/screens/Discussions/index.tsx
  front-end/src/screens/Home/HomeContent.tsx
  front-end/src/screens/OnChain/index.tsx
  front-end/src/screens/SignupForm/index.tsx
  front-end/src/themes/theme.ts
  front-end/src/ui-components/InfoBox.tsx
Labels: PR-1-please review

#283 Proposal bot consistency and cleanup
  auth-server/README.md
  auth-server/docker-compose-test.yaml
  auth-server/src/services/auth.ts
  chain-db-watcher/README.md
  chain-db-watcher/src/graphql_helpers.ts
  kubernetes/polkassembly/auth-server-config.yaml
  kubernetes/polkassembly/auth-server-deployment.yaml
  kubernetes/polkassembly/chain-db-watcher-config.yaml
  kubernetes/polkassembly/chain-db-watcher-deployment.yaml
Labels: PR-1-please review

#330 Added address dropdown for vote and second
  front-end/src/components/Post/Democracy.tsx
  front-end/src/components/Post/SecondProposal.tsx
  front-end/src/components/Post/VoteRefrendum.tsx
  front-end/src/screens/Settings/address.tsx
  front-end/src/util/shortenAddress.ts
Labels: PR-6-got comments

#334 Update chain-db-watcher-deployment.yaml
  kubernetes/polkassembly/chain-db-watcher-deployment.yaml
Labels: PR-1-please review

#338 Added nginx conf in front-end folder and copy step in dockerfile
  front-end/Dockerfile
  front-end/nginx.conf
  kubernetes/polkassembly/front-end-deployment.yaml
  kubernetes/polkassembly/front-end-nginx-config.yaml
Labels: PR-1-please review

#341 Governance info design fix
  front-end/src/components/Post/PostMotionInfo.tsx
  front-end/src/components/Post/PostProposalInfo.tsx
  front-end/src/components/Post/PostReferendumInfo.tsx
Labels: PR-1-please review

#346 Using domain name and domain protocol env vars
  auth-server/README.md
  auth-server/src/services/email.ts
Labels: PR-1-please review

#343 Asking user to install appropriate browser to use vote and seconding
  front-end/src/components/ExtensionNotDetected.tsx
  front-end/src/components/Post/Democracy.tsx
  front-end/src/screens/Settings/address.tsx
Labels: PR-1-please review

#351 UI breakpoint fixes #342 and #348
  front-end/src/components/Post/PostContent.tsx
  front-end/src/screens/LoginForm/index.tsx
  front-end/src/screens/SignupForm/index.tsx
Labels: PR-1-please review

#324 T&C and Privacy Policy pages, basic footer
  front-end/src/App.tsx
  front-end/src/assets/privacy-policy.ts
  front-end/src/assets/terms-and-conditions.ts
  front-end/src/screens/Footer/index.tsx
  front-end/src/screens/Home/index.tsx
  front-end/src/screens/PrivacyPolicy/index.tsx
  front-end/src/screens/SignupForm/index.tsx
  front-end/src/screens/TermsAndConditions/index.tsx
  front-end/src/themes/theme.ts
  front-end/src/ui-components/Form.tsx
  front-end/src/ui-components/GlobalStyle.tsx
Labels: PR-1-please review

#365 Grey hues
  front-end/src/components/DiscussionCard.tsx
  front-end/src/components/GovernanceCard.tsx
  front-end/src/themes/theme.ts
Labels: PR-1-please review

#388 Update T&Cs and legal requirements
  front-end/src/App.tsx
  front-end/src/assets/privacy-policy.ts
  front-end/src/assets/terms-and-conditions.ts
  front-end/src/assets/terms-of-website.ts
  front-end/src/components/Footer/index.tsx
  front-end/src/components/MenuBar/index.tsx
  front-end/src/components/MenuBar/query.ts
  front-end/src/screens/LegalDocuments/index.tsx
  front-end/src/screens/PrivacyPolicy/index.tsx
  front-end/src/screens/SignupForm/index.tsx
  front-end/src/screens/TermsAndConditions/index.tsx
  front-end/src/ui-components/Markdown.tsx
Labels: PR-1-please review

#374 new stage: post-deploy
  .gitlab-ci.yml
Labels: PR-1-please review

#394 Fix passed border
  front-end/src/ui-components/StatusTag.tsx
Labels: PR-2-insubstantial

#397 Folder structure refactoring
  front-end/src/components/Post/GovernanceSideBar/SecondProposal.tsx
  front-end/src/components/Post/GovernanceSideBar/VoteRefrendum.tsx
  front-end/src/components/Post/GovernanceSideBar/index.tsx
  front-end/src/components/Post/Post.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostMotionInfo.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostProposalInfo.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostReferendumInfo.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/screens/Settings/address.tsx
  front-end/src/ui-components/Address.tsx
Labels: PR-1-please review

#404 Hide voting component when not active
  front-end/src/components/GovernanceCard.tsx
  front-end/src/components/Post/GovernanceSideBar/index.tsx
  front-end/src/components/Post/Post.tsx
  front-end/src/global/statuses.ts
  front-end/src/ui-components/StatusTag.tsx
Labels: PR-1-please review

#395 Color and font variables
  front-end/package.json
  front-end/src/components/ContentForm.tsx
  front-end/src/components/MenuBar/index.tsx
  front-end/src/components/Post/Post.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostMotionInfo.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostProposalInfo.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostReferendumInfo.tsx
  front-end/src/components/TitleForm.tsx
  front-end/src/screens/CreatePost/TopicsRadio.tsx
  front-end/src/screens/LoginForm/index.tsx
  front-end/src/screens/Settings/address.tsx
  front-end/src/screens/Settings/email.tsx
  front-end/src/screens/SignupForm/index.tsx
  front-end/src/ui-components/Button.tsx
  front-end/src/ui-components/DismissableNotification.tsx
  front-end/src/ui-components/FilteredError.tsx
  front-end/src/ui-components/Form.tsx
  front-end/src/ui-components/GlobalStyle.tsx
  front-end/src/ui-components/InfoBox.tsx
  front-end/src/ui-components/Input.tsx
  front-end/src/ui-components/Modal.tsx
  front-end/src/ui-components/TextArea.tsx
Labels: PR-1-please review

#385 Markdown style component
  front-end/package.json
  front-end/src/components/Comment/Comment.tsx
  front-end/src/components/Comment/EditableCommentContent.tsx
  front-end/src/components/ContentForm.tsx
  front-end/src/components/MenuBar/index.tsx
  front-end/src/components/Post/Post.tsx
  front-end/src/components/Post/PostContent.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostMotionInfo.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostProposalInfo.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostReferendumInfo.tsx
  front-end/src/components/TitleForm.tsx
  front-end/src/screens/CreatePost/TopicsRadio.tsx
  front-end/src/screens/Home/index.tsx
  front-end/src/screens/LoginForm/index.tsx
  front-end/src/screens/OnChain/index.tsx
  front-end/src/screens/Settings/address.tsx
  front-end/src/screens/Settings/email.tsx
  front-end/src/screens/Settings/index.tsx
  front-end/src/screens/SignupForm/index.tsx
  front-end/src/ui-components/Button.tsx
  front-end/src/ui-components/CreationLabel.tsx
  front-end/src/ui-components/DismissableNotification.tsx
  front-end/src/ui-components/FilteredError.tsx
  front-end/src/ui-components/Form.tsx
  front-end/src/ui-components/GlobalStyle.tsx
  front-end/src/ui-components/InfoBox.tsx
  front-end/src/ui-components/Input.tsx
  front-end/src/ui-components/Markdown.tsx
  front-end/src/ui-components/Modal.tsx
  front-end/src/ui-components/TextArea.tsx
  front-end/src/ui-components/UpdateLabel.tsx
Labels: PR-1-please review

#407 Getting remote schema url from env vars
  hasura/docker-compose.yaml.example
  hasura/hasura-migrations/migrations/1582552076335_table_posts_drop_remote_relationship_author/down.yaml
  hasura/hasura-migrations/migrations/1582552076335_table_posts_drop_remote_relationship_author/up.yaml
  hasura/hasura-migrations/migrations/1582552087743_table_comments_drop_remote_relationship_author/down.yaml
  hasura/hasura-migrations/migrations/1582552087743_table_comments_drop_remote_relationship_author/up.yaml
  hasura/hasura-migrations/migrations/1582552105476_update_remote_schema_auth/down.yaml
  hasura/hasura-migrations/migrations/1582552105476_update_remote_schema_auth/up.yaml
  hasura/hasura-migrations/migrations/1582552134767_table_posts_create_remote_relationship_author/down.yaml
  hasura/hasura-migrations/migrations/1582552134767_table_posts_create_remote_relationship_author/up.yaml
  hasura/hasura-migrations/migrations/1582552151971_table_comments_create_remote_relationship_author/down.yaml
  hasura/hasura-migrations/migrations/1582552151971_table_comments_create_remote_relationship_author/up.yaml
  hasura/hasura-migrations/migrations/1582552229731_table_onchain_links_drop_remote_relationship_onchain_proposal/down.yaml
  hasura/hasura-migrations/migrations/1582552229731_table_onchain_links_drop_remote_relationship_onchain_proposal/up.yaml
  hasura/hasura-migrations/migrations/1582552237735_table_onchain_links_drop_remote_relationship_onchain_referendum/down.yaml
  hasura/hasura-migrations/migrations/1582552237735_table_onchain_links_drop_remote_relationship_onchain_referendum/up.yaml
  hasura/hasura-migrations/migrations/1582552248166_table_onchain_links_drop_remote_relationship_onchain_motion/down.yaml
  hasura/hasura-migrations/migrations/1582552248166_table_onchain_links_drop_remote_relationship_onchain_motion/up.yaml
  hasura/hasura-migrations/migrations/1582552281519_update_remote_schema_chain-db/down.yaml
  hasura/hasura-migrations/migrations/1582552281519_update_remote_schema_chain-db/up.yaml
  hasura/hasura-migrations/migrations/1582552468902_table_onchain_links_create_remote_relationship_onchain_proposal/down.yaml
  hasura/hasura-migrations/migrations/1582552468902_table_onchain_links_create_remote_relationship_onchain_proposal/up.yaml
  hasura/hasura-migrations/migrations/1582552496160_table_onchain_links_create_remote_relationship_onchain_referendum/down.yaml
  hasura/hasura-migrations/migrations/1582552496160_table_onchain_links_create_remote_relationship_onchain_referendum/up.yaml
  hasura/hasura-migrations/migrations/1582552517341_table_onchain_links_create_remote_relationship_onchain_motion/down.yaml
  hasura/hasura-migrations/migrations/1582552517341_table_onchain_links_create_remote_relationship_onchain_motion/up.yaml
  kubernetes/polkassembly/hasura-config.yaml
  kubernetes/polkassembly/hasura-deployment.yaml
Labels: PR-1-please review

#409 Fix onchain links
  hasura/hasura-migrations/migrations/1582631584192_table_onchain_links_create_remote_relationship_onchain_proposal/down.yaml
  hasura/hasura-migrations/migrations/1582631584192_table_onchain_links_create_remote_relationship_onchain_proposal/up.yaml
  hasura/hasura-migrations/migrations/1582631619424_table_onchain_links_drop_remote_relationship_onchain_proposal/down.yaml
  hasura/hasura-migrations/migrations/1582631619424_table_onchain_links_drop_remote_relationship_onchain_proposal/up.yaml
  hasura/hasura-migrations/migrations/1582631659991_table_onchain_links_create_remote_relationship_onchain_referendum/down.yaml
  hasura/hasura-migrations/migrations/1582631659991_table_onchain_links_create_remote_relationship_onchain_referendum/up.yaml
  hasura/hasura-migrations/migrations/1582631766314_table_onchain_links_create_remote_relationship_onchain_motion/down.yaml
  hasura/hasura-migrations/migrations/1582631766314_table_onchain_links_create_remote_relationship_onchain_motion/up.yaml
  hasura/hasura-migrations/migrations/1582631823541_table_onchain_links_create_remote_relationship_onchain_proposal/down.yaml
  hasura/hasura-migrations/migrations/1582631823541_table_onchain_links_create_remote_relationship_onchain_proposal/up.yaml
Labels: PR-1-please review

#419 Form fix
  front-end/src/ui-components/Form.tsx
Labels: PR-1-please review

#416 Disapproved status tag fix
  front-end/src/components/GovernanceCard.tsx
Labels: PR-1-please review

#412 Menu with logo
  front-end/src/assets/polkassembly-logo.png
  front-end/src/components/MenuBar/index.tsx
  front-end/src/fonts.css
  front-end/src/import-png.d.ts
  front-end/src/themes/theme.ts
Labels: PR-1-please review

#415 Polkadot Pink
  front-end/src/components/Comment/EditableCommentContent.tsx
  front-end/src/components/DiscussionCard.tsx
  front-end/src/components/EditablePostContent.tsx
  front-end/src/components/GovernanceCard.tsx
  front-end/src/components/Post/GovernanceSideBar/VoteRefrendum.tsx
  front-end/src/components/Post/PostCommentForm.tsx
  front-end/src/screens/Settings/address.tsx
  front-end/src/themes/theme.ts
  front-end/src/ui-components/Button.tsx
  front-end/src/ui-components/Markdown.tsx
Labels: PR-1-please review
