Repository paritytech/polkassembly, pull requests merged in 2020-07, with the labels that each got.

#952 Show poll end time
  front-end/src/components/BlockCountdown.tsx
  front-end/src/components/Post/Poll/GeneralSignals.tsx
Labels: PR-6-got comments

#925 Showing error on subscribing to post if email is not verified
  auth-server/src/resolvers/mutation/postSubscribe.ts
  auth-server/src/utils/messages.ts
  auth-server/test/resolvers/mutation/postSubscribe.spec.ts
  auth-server/test/resolvers/mutation/postUnsubscribe.spec.ts
  front-end/src/components/SubscriptionButton/SubscriptionButton.tsx
  front-end/src/screens/CreatePost/index.tsx
  front-end/src/screens/NotificationSettings/index.tsx
Labels: PR-1-please review

#953 Show no current tip only if no current tip
  front-end/src/components/Listings/TipListing.tsx
Labels: PR-1-please review, x- changelog-fix

#954 Add at in tip creation query
  node-watcher/src/tasks/createTipStatus.ts
Labels: PR-1-please review

#955 Bump @polkadot/api 1.23
  auth-server/package.json
  auth-server/test/resolvers/query/subscription.spec.ts
  auth-server/yarn.lock
  front-end/package.json
  front-end/yarn.lock
  health-monitor/package.json
  health-monitor/yarn.lock
  node-watcher/package.json
  node-watcher/src/nodeWatcher.ts
  node-watcher/yarn.lock
Labels: PR-1-please review

#961 Bum polkadot api 1.24
  auth-server/package.json
  auth-server/yarn.lock
  front-end/package.json
  front-end/yarn.lock
  health-monitor/package.json
  health-monitor/yarn.lock
  node-watcher/package.json
  node-watcher/yarn.lock
Labels: x- changelog-chore

#970 Bump polkadot api 1.25
  auth-server/package.json
  auth-server/yarn.lock
  front-end/package.json
  front-end/yarn.lock
  health-monitor/package.json
  health-monitor/yarn.lock
  node-watcher/package.json
  node-watcher/yarn.lock
Labels: PR-1-please review, x- changelog-chore

#960 Added external links to subscan and polkascan
  front-end/src/components/ExternalLinks.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostMotionInfo.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostProposalInfo.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostReferendumInfo.tsx
  front-end/src/components/Post/PostGovernanceInfo/PostTreasuryInfo.tsx
  front-end/src/ui-components/Button.tsx
Labels: PR-1-please review, x- changelog-feature

#976 Fixed ordering for tips
  front-end/src/generated/graphql.tsx
  front-end/src/screens/Motions/index.tsx
  front-end/src/screens/OnChain/Tips/query.ts
  front-end/src/screens/Proposals/index.tsx
  front-end/src/screens/Referenda/index.tsx
  front-end/src/screens/Tips/TipContainer/query.ts
  front-end/src/screens/Tips/index.tsx
  front-end/src/screens/Treasury/index.tsx
Labels: PR-1-please review, x- changelog-feature
