Repository paritytech/polkassembly, pull requests merged in 2020-01, with the labels that each got.

#177 Added return type
  auth-server/src/resolvers/mutation/changeEmail.ts
  auth-server/src/resolvers/mutation/changeName.ts
  auth-server/src/resolvers/mutation/changePassword.ts
  auth-server/src/resolvers/mutation/changeUsername.ts
  auth-server/src/resolvers/mutation/login.ts
  auth-server/src/resolvers/mutation/logout.ts
  auth-server/src/resolvers/mutation/requestResetPassword.ts
  auth-server/src/resolvers/mutation/resetPassword.ts
  auth-server/src/resolvers/mutation/signup.ts
  auth-server/src/resolvers/mutation/verifyEmail.ts
  auth-server/src/resolvers/query/token.ts
  auth-server/src/resolvers/query/user.ts
  auth-server/src/resolvers/query/users.ts
  auth-server/src/types.ts
Labels: PR-1-please review

#180 Added docs for changeEmail.
  auth-server/README.md
Labels: PR-1-please review

#183 Changed post creation title font size to 1.4rem
  front-end/src/components/PostOrCommentForm.tsx
Labels: PR-1-please review

#188 Notifications alignment
  front-end/src/screens/Comment/EditableCommentContent.tsx
  front-end/src/screens/Post/EditablePostContent.tsx
  front-end/src/ui-components/DisapearingLabel.tsx
Labels: PR-1-please review

#176 Email verification refactor
  auth-server/README.md
  auth-server/src/resolvers/mutation/verifyEmail.ts
  auth-server/src/schema/mutation/verifyEmail.ts
  auth-server/src/services/auth.ts
  auth-server/test/resolvers/mutation/verifyEmail.spec.ts
  front-end/src/generated/auth-graphql.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/screens/Settings/email.tsx
  front-end/src/screens/VerifyEmail/index.tsx
  front-end/src/screens/VerifyEmail/query.ts
Labels: PR-1-please review

#186 Fix settings
  front-end/src/screens/Settings/email.tsx
  front-end/src/screens/Settings/fullname.tsx
  front-end/src/screens/Settings/index.tsx
  front-end/src/screens/Settings/password.tsx
  front-end/src/screens/Settings/username.tsx
Labels: PR-1-please review

#185 Filter errors
  front-end/src/screens/CreatePost/TopicsRadio.tsx
  front-end/src/screens/CreatePost/index.tsx
  front-end/src/screens/Discussions/index.tsx
  front-end/src/screens/Home/index.tsx
  front-end/src/screens/LoginForm/index.tsx
  front-end/src/screens/Post/CreateRootComment.tsx
  front-end/src/screens/Post/EditablePostContent.tsx
  front-end/src/screens/Post/index.tsx
  front-end/src/screens/Proposals/index.tsx
  front-end/src/screens/RequestResetPassword/ResetPassword/index.tsx
  front-end/src/screens/RequestResetPassword/index.tsx
  front-end/src/screens/Settings/email.tsx
  front-end/src/screens/Settings/fullname.tsx
  front-end/src/screens/Settings/password.tsx
  front-end/src/screens/Settings/username.tsx
  front-end/src/screens/SignupForm/index.tsx
  front-end/src/screens/VerifyEmail/index.tsx
  front-end/src/ui-components/FilteredError.tsx
Labels: PR-1-please review

#190 Comment styling
  front-end/src/screens/Comment/Comment.tsx
  front-end/src/screens/Comment/Comments.tsx
  front-end/src/screens/Comment/EditableCommentContent.tsx
  front-end/src/screens/Post/Post.tsx
  front-end/src/ui-components/CreationLabel.tsx
  front-end/src/ui-components/UpdateLabel.tsx
Labels: PR-1-please review

#192 Added pagination to users query
  auth-server/src/resolvers/query/users.ts
  auth-server/src/schema/query/users.ts
  auth-server/test/resolvers/query/users.spec.ts
  auth-server/test/rewiremock.ts
  auth-server/test/services/email/email.spec.ts
Labels: PR-1-please review

#199 Validation for login signup
  front-end/src/screens/LoginForm/index.tsx
  front-end/src/screens/SignupForm/index.tsx
  front-end/src/ui-components/FilteredError.tsx
  front-end/src/util/messages.ts
Labels: PR-1-please review

#198 Small styling nits
  auth-server/README.md
  auth-server/src/services/email.ts
  front-end/src/components/Modal.tsx
  front-end/src/screens/Comment/Comment.tsx
  front-end/src/screens/Comment/EditableCommentContent.tsx
  front-end/src/screens/CreatePost/index.tsx
  front-end/src/screens/Post/CreateRootComment.tsx
  front-end/src/screens/Post/EditablePostContent.tsx
  front-end/src/screens/Settings/email.tsx
  front-end/src/screens/Settings/fullname.tsx
  front-end/src/screens/Settings/index.tsx
  front-end/src/screens/Settings/password.tsx
  front-end/src/screens/Settings/username.tsx
  front-end/src/ui-components/Button.tsx
  front-end/src/ui-components/DismissableNotification.tsx
Labels: PR-1-please review

#209 xstyled theming setup
  front-end/package.json
  front-end/src/App.tsx
  front-end/src/components/ContentForm.tsx
  front-end/src/components/DiscussionCard.tsx
  front-end/src/screens/Comment/Comments.tsx
  front-end/src/themes/theme.ts
  front-end/src/themes/xstyled.d.ts
  front-end/src/ui-components/Button.tsx
  front-end/src/ui-components/GlobalStyle.tsx
  front-end/yarn.lock
Labels: PR-3-in progress

#210 Remove checkboxes
  front-end/src/screens/Comment/Comment.tsx
  front-end/src/screens/Post/Post.tsx
  front-end/src/ui-components/TextArea.tsx
Labels: PR-1-please review

#216 added 404 page
  front-end/public/broken-chain.png
  front-end/src/App.tsx
  front-end/src/screens/NotFound/index.tsx
Labels: PR-1-please review

#227 Add yarn to the auth and front steps in launch.sh
  launch.sh
Labels: PR-2-insubstantial

#224 Mobile menu
  front-end/src/App.tsx
  front-end/src/screens/Discussions/Discussions.tsx
  front-end/src/screens/Home/HomeContent.tsx
  front-end/src/screens/MenuBar/index.tsx
  front-end/src/ui-components/GlobalStyle.tsx
Labels: PR-1-please review

#217 link/unlink kasuma/polkadot address
  auth-server/migrations/20200113102520_address.js
  auth-server/package.json
  auth-server/src/model/Address.ts
  auth-server/src/resolvers/index.ts
  auth-server/src/resolvers/mutation/addressLinkConfirm.ts
  auth-server/src/resolvers/mutation/addressLinkStart.ts
  auth-server/src/resolvers/mutation/addressUnlink.ts
  auth-server/src/resolvers/query/addresses.ts
  auth-server/src/schema/index.ts
  auth-server/src/schema/mutation/addressLinkConfirm.ts
  auth-server/src/schema/mutation/addressLinkStart.ts
  auth-server/src/schema/mutation/addressUnlink.ts
  auth-server/src/schema/query/addresses.ts
  auth-server/src/schema/type/address.ts
  auth-server/src/schema/type/addressLinkType.ts
  auth-server/src/types.ts
  auth-server/src/utils/messages.ts
  auth-server/yarn.lock
  front-end/package.json
  front-end/src/generated/auth-graphql.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/screens/Settings/address.tsx
  front-end/src/screens/Settings/index.tsx
  front-end/src/screens/Settings/query.ts
  front-end/src/types.ts
  front-end/src/util/getExtensionUrl.ts
  front-end/yarn.lock
Labels: PR-1-please review

#235 Made email, name optional
  auth-server/migrations/20180917160913_users.js
  auth-server/src/model/User.ts
  auth-server/src/resolvers/mutation/signup.ts
  auth-server/src/schema/mutation/signup.ts
  auth-server/src/services/auth.ts
  front-end/src/generated/auth-graphql.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/screens/SignupForm/index.tsx
  front-end/src/services/auth-queries.ts
  front-end/src/util/messages.ts
Labels: PR-6-got comments

#245 Sign-up explanations
  front-end/src/screens/SignupForm/index.tsx
  front-end/src/ui-components/Form.tsx
Labels: PR-1-please review

#248 Link referenda to existing proposal if any
  README.md
  chain-db-watcher/.eslintrc.json
  chain-db-watcher/package.json
  chain-db-watcher/src/graphql_helpers.ts
  chain-db-watcher/src/index.ts
  chain-db-watcher/src/queries.ts
  chain-db-watcher/tsconfig-bis.json
  chain-db-watcher/tsconfig.json
  chain-db-watcher/yarn.lock
  hasura/hasura-migrations/migrations/1580148698331_table_onchain_proposals_drop_remote_relationship_proposal/down.yaml
  hasura/hasura-migrations/migrations/1580148698331_table_onchain_proposals_drop_remote_relationship_proposal/up.yaml
  hasura/hasura-migrations/migrations/1580148716134_rename_table_public_onchain_proposals/down.yaml
  hasura/hasura-migrations/migrations/1580148716134_rename_table_public_onchain_proposals/up.yaml
  hasura/hasura-migrations/migrations/1580148790706_table_onchain_links_create_remote_relationship_onchain_proposal/down.yaml
  hasura/hasura-migrations/migrations/1580148790706_table_onchain_links_create_remote_relationship_onchain_proposal/up.yaml
  hasura/hasura-migrations/migrations/1580149006511_alter_table_public_onchain_links_add_column_onchain_referendum_id/down.yaml
  hasura/hasura-migrations/migrations/1580149006511_alter_table_public_onchain_links_add_column_onchain_referendum_id/up.yaml
  hasura/hasura-migrations/migrations/1580149017783_alter_table_public_onchain_links_alter_column_onchain_proposal_id/down.yaml
  hasura/hasura-migrations/migrations/1580149017783_alter_table_public_onchain_links_alter_column_onchain_proposal_id/up.yaml
  hasura/hasura-migrations/migrations/1580149055449_update_permission_anonymous_public_table_onchain_links/down.yaml
  hasura/hasura-migrations/migrations/1580149055449_update_permission_anonymous_public_table_onchain_links/up.yaml
  hasura/hasura-migrations/migrations/1580149062208_update_permission_proposal_bot_public_table_onchain_links/down.yaml
  hasura/hasura-migrations/migrations/1580149062208_update_permission_proposal_bot_public_table_onchain_links/up.yaml
  hasura/hasura-migrations/migrations/1580149076860_update_permission_proposal_bot_public_table_onchain_links/down.yaml
  hasura/hasura-migrations/migrations/1580149076860_update_permission_proposal_bot_public_table_onchain_links/up.yaml
  hasura/hasura-migrations/migrations/1580149138051_update_permission_proposal_bot_public_table_onchain_links/down.yaml
  hasura/hasura-migrations/migrations/1580149138051_update_permission_proposal_bot_public_table_onchain_links/up.yaml
  hasura/hasura-migrations/migrations/1580149171516_table_onchain_links_create_remote_relationship_onchain_referendum/down.yaml
  hasura/hasura-migrations/migrations/1580149171516_table_onchain_links_create_remote_relationship_onchain_referendum/up.yaml
  hasura/hasura-migrations/migrations/1580167344799_rename_relationship_onchain_proposal_to_onchain_link_schema_public_table_posts/down.yaml
  hasura/hasura-migrations/migrations/1580167344799_rename_relationship_onchain_proposal_to_onchain_link_schema_public_table_posts/up.yaml
Labels: PR-1-please review

#252 added public user type and name fix for frontend
  auth-server/src/schema/index.ts
  auth-server/src/schema/query/users.ts
  auth-server/src/schema/type/publicUser.ts
  front-end/src/screens/SignupForm/index.tsx
Labels: PR-1-please review

#250 Show display name (username popover)
  front-end/src/components/DiscussionCard.tsx
  front-end/src/components/PostContent.tsx
  front-end/src/generated/auth-graphql.tsx
  front-end/src/generated/graphql.tsx
  front-end/src/screens/Comment/Comment.tsx
  front-end/src/screens/Discussions/Discussions.tsx
  front-end/src/screens/Discussions/query.ts
  front-end/src/screens/Home/HomeContent.tsx
  front-end/src/screens/Home/query.ts
  front-end/src/screens/Post/query.ts
  front-end/src/screens/Proposals/Proposals.tsx
  front-end/src/screens/Proposals/query.ts
  front-end/src/screens/Settings/fullname.tsx
  front-end/src/ui-components/CreationLabel.tsx
Labels: PR-6-got comments

#247 Added header x-hasura-kusama as kasuma address array
  auth-server/migrations/20200113102520_address.js
  auth-server/src/model/Address.ts
  auth-server/src/resolvers/mutation/addressLinkConfirm.ts
  auth-server/src/resolvers/mutation/addressLinkStart.ts
  auth-server/src/resolvers/query/addresses.ts
  auth-server/src/services/auth.ts
  auth-server/src/types.ts
  auth-server/src/utils/getAddressesFromUserId.ts
  hasura/hasura-migrations/migrations/1580286221713_update_permission_user_public_table_posts/down.yaml
  hasura/hasura-migrations/migrations/1580286221713_update_permission_user_public_table_posts/up.yaml
Labels: PR-1-please review

#258 Storybook setup
  front-end/.storybook/addons.ts
  front-end/.storybook/config.ts
  front-end/.storybook/webpack.config.ts
  front-end/package.json
  front-end/src/test/__snapshots__/storyshots.test.ts.snap
  front-end/src/test/storyshots.test.ts
  front-end/src/ui-components/stories/Button.stories.tsx
  front-end/src/ui-components/stories/customDecorators/withTheme.tsx
  front-end/yarn.lock
Labels: PR-1-please review

#268 Docker retry
  auth-server/docker-compose-test.yaml
  auth-server/package.json
Labels: PR-1-please review

#271 Several styled-components instances fix
  front-end/package.json
  front-end/yarn.lock
Labels: PR-1-please review
